//! Unix-socket frames spoken at `~/.codeconnect/ccd.sock`.
//!
//! Newline-delimited JSON, one frame per line. Two kinds of client connect:
//!
//!   * **cc-hook** — one `Hook` frame, then either exits immediately
//!     (observability) or reads exactly one `HookReply` (gate events).
//!   * **supervisor** — one `Register` frame, then stays connected for the life
//!     of the session. The daemon pushes `SupervisorRequest`s down this socket.
//!
//! The supervisor connects *out* to the daemon, never the reverse. That is what
//! keeps `ccd` out of the agents' process-parent chain, so `kill -9 ccd` cannot
//! take a session with it: the daemon is an observer, and killing an observer
//! must never kill what it was observing.

use serde::{Deserialize, Serialize};

use crate::event::SessionSummary;
use crate::hook::HookDecision;

/// Frames larger than this are a bug or an attack; the reader drops the
/// connection rather than growing its buffer without bound. Tool responses of a
/// few hundred KB are normal, so the ceiling is generous.
pub const MAX_FRAME_BYTES: usize = 8 * 1024 * 1024;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientFrame {
    Hook(HookPost),
    Register(RegisterSession),
    /// **Pre-`Register` support negotiation.** A supervisor asks, on the same
    /// connection and *before* it registers, whether this daemon can host its
    /// agent — so it can withhold `Register` (and retry with backoff) rather than
    /// introduce a session a rolled-back daemon would mishandle. The daemon
    /// answers [`DaemonFrame::SupportedAgents`].
    ///
    /// Defined at the agent seam (minor 15); the negotiation *flow* that consumes
    /// it lands with the Codex launcher. A Claude supervisor has no reason to
    /// send it — absence still means Claude, which every daemon supports.
    NegotiateSupport {
        /// The agent the supervisor intends to register.
        #[serde(default)]
        agent: crate::agent::AgentKind,
        /// The resolved agent version, when known, for the daemon's own pin.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agent_version: Option<String>,
    },
    SupervisorResponse {
        id: String,
        result: SupervisorResult,
    },
    Heartbeat {
        session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_uid: Option<String>,
    },
    /// Reported over a *fresh* connection, after the session is already gone, so
    /// it has to carry its own identity — there is no registered socket left to
    /// infer it from, and a bare `cc-1` could by then belong to a new run.
    SessionExited {
        session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_uid: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        exit_code: Option<i32>,
        /// Why the run ended, when the process that ended it can say something the
        /// exit code cannot — today, only "the codex TUI exited without a thread
        /// ever binding", asserted by the host and relayed verbatim by the
        /// supervisor that read it off the launch record.
        ///
        /// **Absent means "nothing was asserted", never "it ended cleanly."** The
        /// daemon files it as the `session_end` payload's `reason` when present and
        /// files no reason at all when not; it does not infer one. An older
        /// supervisor omits the field and an older daemon ignores it, so this is
        /// additive in both directions and needs no minor bump.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },
    ListSessions,
    /// `codeconnect sessions prune`. Remove the runs that have **ended**, and their
    /// events, from the log.
    ///
    /// Asked for explicitly and never done on a schedule: the event log is the
    /// source of truth, and a daemon that decided on its own which of an
    /// operator's agent history to discard would be making that call for them.
    /// The daemon is what performs it, rather than the shim reaching into the
    /// database, because only the daemon knows which runs it still holds live
    /// state for — and because two writers to one SQLite file is the shape of
    /// problem this codebase spent its `BEGIN IMMEDIATE` avoiding.
    PruneSessions {
        /// Report what would go without removing anything.
        #[serde(default)]
        dry_run: bool,
    },
    /// `codeconnect pair`. The daemon mints and stores the code, because it is the only
    /// process that will later be asked to honour it — a code generated by the
    /// shim and handed over would have to survive a daemon restart in a second
    /// place, for no benefit.
    CreatePairing {
        #[serde(default)]
        ttl_secs: u64,
        /// `codeconnect pair --ssh` on a shim from before this daemon.
        ///
        /// Older CLIs may still send this; a true value is refused before
        /// anything is mutated. See [`ClientFrame::ssh_refusal`].
        #[serde(default)]
        allow_ssh: bool,
    },
    ListDevices,
    /// `codeconnect revoke <device>`.
    RevokeDevice {
        /// A device id, a device id prefix, or an exact name.
        device: String,
        /// `codeconnect ssh-revoke <device>` on a shim from before this daemon.
        ///
        /// Older CLIs may still send this; a true value is refused before
        /// anything is mutated. See [`ClientFrame::ssh_refusal`].
        #[serde(default)]
        ssh_only: bool,
    },
    /// "Who is answering this socket?" — asked by `codeconnect daemon status` and by
    /// `codeconnect daemon install` before it decides whether it is about to fight a
    /// daemon somebody started by hand.
    ///
    /// Asked over the socket rather than read from a pidfile: a pidfile can
    /// outlive its process and name a pid that now belongs to something else,
    /// and `codeconnect daemon install` uses this answer to send a signal.
    DaemonInfo,
}

impl ClientFrame {
    /// Why this frame is refused, when it asks the daemon to manage an SSH key.
    ///
    /// `ccd` grants a device token and nothing else; the only thing it does
    /// near `~/.ssh` is remove, at startup, the entries earlier releases
    /// installed. A shim from an earlier release still carries flags asking
    /// for key management, and answering one with the ordinary success frame
    /// would tell the operator a key was installed or revoked when nothing of
    /// the sort happened. The caller sends this message back instead, and
    /// performs no part of the request.
    ///
    /// `Some` only for a flag set *true*: absent and `false` both mean the
    /// command carried no such request, and those proceed normally.
    pub fn ssh_refusal(&self) -> Option<&'static str> {
        match self {
            ClientFrame::CreatePairing {
                allow_ssh: true, ..
            } => Some(
                "this daemon does not manage SSH keys; re-run `codeconnect pair` \
                 without --ssh, or update the codeconnect CLI",
            ),
            ClientFrame::RevokeDevice { ssh_only: true, .. } => Some(
                "this daemon does not manage SSH keys; use `codeconnect revoke <device>` \
                 to revoke the device itself, or update the codeconnect CLI",
            ),
            _ => None,
        }
    }
}

/// A wire field that is always `false`.
///
/// A shim from an earlier release fails to decode a `pairing` or `revoked`
/// frame that omits its SSH field, so the field is still serialized — and
/// serialized as a type that cannot carry any other value, which is the whole
/// truth about a daemon that does not manage SSH keys. Any value is accepted on
/// the way in, because an older *daemon* answering a current shim may send
/// `true`, and nothing here reads it.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct AlwaysFalse;

impl Serialize for AlwaysFalse {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_bool(false)
    }
}

impl<'de> Deserialize<'de> for AlwaysFalse {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        bool::deserialize(deserializer)?;
        Ok(AlwaysFalse)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum DaemonFrame {
    HookReply {
        decision: HookDecision,
    },
    Ack,
    Error {
        message: String,
    },
    /// The daemon's answer to [`ClientFrame::NegotiateSupport`]: the agents it
    /// can actually host, and whether the asked-for agent is among them. A
    /// supervisor that finds its agent absent withholds `Register` and retries.
    /// `supported` is the specific verdict for the negotiated agent, so the
    /// supervisor need not re-derive it from the list (and an unknown agent is
    /// unambiguously `false`).
    SupportedAgents {
        supported_agents: Vec<crate::agent::AgentKind>,
        supported: bool,
    },
    SupervisorRequest {
        id: String,
        request: SupervisorRequest,
    },
    Sessions {
        sessions: Vec<SessionSummary>,
    },
    /// Everything `codeconnect pair` needs to draw the QR. The host and port come from
    /// the daemon rather than being re-derived by the shim: the daemon already
    /// resolved them to decide what to bind and whether it holds a certificate,
    /// and two independent answers to "where am I reachable" is exactly how a
    /// QR ends up pointing somewhere nothing is listening.
    Pairing {
        code: String,
        expires_at: String,
        host: String,
        port: u16,
        /// True when the daemon serves `wss://`, so the shim can tell the
        /// operator which scheme the phone will use.
        tls: bool,
        /// A shim from an earlier release requires this field to decode the
        /// frame at all.
        #[serde(default)]
        allow_ssh: AlwaysFalse,
    },
    Devices {
        devices: Vec<crate::pairing::DeviceSummary>,
    },
    /// What `codeconnect sessions prune` removed, or would have.
    ///
    /// The removed runs are listed rather than counted. Deleting somebody's
    /// history is the operation that most has to be able to say what it did,
    /// and afterwards there is nothing left to check it against.
    Pruned {
        removed: Vec<PrunedSummary>,
        /// Runs left in place because they are still going.
        kept_live: usize,
        /// Runs left in place because nothing could be established about them.
        /// Deliberately reported separately from `kept_live`: "still running"
        /// and "we do not know what happened to this" are different reasons to
        /// keep something, and the second is the one an operator may want to
        /// look into.
        kept_unknown: usize,
        /// Runs that *had* ended and still were not removed, because the daemon
        /// is holding live state for them — a supervisor still attached, or an
        /// approval still open.
        ///
        /// Reported because without it the command lies by omission: it printed
        /// "no ended sessions to remove" while ended sessions sat right there in
        /// `codeconnect sessions`, and named neither them nor the reason. This is the one
        /// count that means "look into this": the daemon holding live state for
        /// a run it has already marked ended is the condition
        /// [`crate::ipc`]'s caller calls a bug, and it clears itself once the
        /// approval ages out.
        #[serde(default)]
        kept_held: usize,
        /// Events belonging to a `session_uid` with no session row at all.
        ///
        /// Nothing reaches these: they are absent from the fleet, from
        /// `codeconnect sessions`, and from the prune, which is defined over session
        /// rows. Counted and reported rather than removed — data whose
        /// provenance is not understood is exactly what an automatic cleanup
        /// must leave alone — so that an operator can at least see it exists.
        #[serde(default)]
        orphan_events: u64,
        dry_run: bool,
    },
    Revoked {
        device: crate::pairing::DeviceSummary,
        /// False when the device was already revoked — reported rather than
        /// treated as an error, so `codeconnect revoke` is idempotent.
        token_revoked: bool,
        /// A shim from an earlier release requires this field to decode the
        /// frame at all.
        #[serde(default)]
        ssh_key_removed: AlwaysFalse,
    },
    Daemon(DaemonInfo),
}

/// One run that `codeconnect sessions prune` removed, and what went with it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrunedSummary {
    pub session_uid: String,
    pub session_id: String,
    pub cwd: String,
    pub created_at: String,
    pub updated_at: String,
    /// Facts deleted along with the run. The number an operator would want
    /// before agreeing to this, which is why `--dry-run` reports it too.
    pub events: u64,
}

/// The daemon's own account of itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaemonInfo {
    pub pid: u32,
    pub version: String,
    pub protocol_version: u32,
    pub protocol_minor: u32,
    pub started_at: String,
    /// The launchd job this process belongs to, taken from `XPC_SERVICE_NAME`.
    ///
    /// `None` means "started some other way" — a foreground `ccd &`, a debugger,
    /// a test. That distinction is the whole reason this field exists: `getppid()
    /// == 1` is true of any orphan, so it cannot tell a launchd job from a
    /// daemon whose parent shell has exited, and installing the LaunchAgent on
    /// top of the latter would leave two processes fighting over one socket.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub launchd_label: Option<String>,
    /// Where the phone is told to connect, so `codeconnect daemon status` can show it
    /// without re-deriving it and getting a different answer.
    pub endpoint_host: String,
    pub endpoint_port: u16,
    pub tls: bool,
    /// The address the WebSocket listener is actually bound to — distinct
    /// from `endpoint_host`, which under TLS is the MagicDNS *name*. The CLI's
    /// reachability advisory keys on this: only a daemon genuinely bound to a
    /// tailnet address is "reachable again the moment the tailnet is back".
    /// Optional so a newer CLI still reads an older daemon's answer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bind_ip: Option<String>,
    /// The running executable's path and content hash, captured at startup.
    /// `codeconnect daemon status` re-hashes the file and says so when the
    /// binary on disk has changed under a still-running daemon — the silent
    /// state two stale deploys in one day proved needs a voice. Optional so
    /// a newer CLI still reads an older daemon's answer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exe_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exe_sha: Option<String>,
    /// The daemon's build tag — `227f6d4e1791`, with `-dirty` when built
    /// from an edited tree. Absent when the daemon predates the field or was
    /// built outside a git checkout; `daemon status` renders that absence as
    /// `build unknown` rather than guessing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub build_id: Option<String>,
    pub sessions: usize,
}

impl DaemonInfo {
    /// True when launchd, and not a human, is responsible for restarting this
    /// process.
    pub fn is_launchd_managed(&self) -> bool {
        self.launchd_label.as_deref() == Some(crate::LAUNCHD_LABEL)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookPost {
    /// CodeConnect session name (`cc-1`), resolved by cc-hook from its
    /// `--session` argument or `CODECONNECT_SESSION`.
    pub session_id: String,
    /// The run's unique identity, from `--session-uid` or
    /// `CODECONNECT_SESSION_UID`.
    ///
    /// Absent for a session started before this existed (its generated settings
    /// file predates the flag) and for a session CodeConnect did not launch at
    /// all. The daemon then resolves the name to the newest live run, or adopts
    /// a fresh identity — so a missing uid degrades to the older name-based
    /// behaviour rather than dropping the fact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    /// `hook_event_name` as Claude reported it.
    pub event: String,
    /// The untouched hook stdin. Stored verbatim as the event payload.
    pub payload: serde_json::Value,
    /// True when the agent is blocked until we answer.
    #[serde(default)]
    pub wait: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegisterSession {
    pub session_id: String,
    /// Minted by `codeconnect claude` at spawn. Optional only so a supervisor left over
    /// from an older build can still register; a new one always sends it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    pub tmux_session: String,
    pub tmux_socket: String,
    pub cwd: String,
    pub supervisor_pid: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_bin: Option<String>,
    /// Which agent this supervisor is hosting. Absent — from a supervisor left
    /// over from a build predating the agent seam — decodes as
    /// [`crate::agent::AgentKind::Claude`], which is exactly what it is. An
    /// **unrecognised** name never decodes as Claude; the daemon fails closed on
    /// it (no adoption, no actuation).
    #[serde(default)]
    pub agent: crate::agent::AgentKind,
    /// The resolved binary this session was launched with, agent-general.
    /// [`claude_bin`](Self::claude_bin) is retained beside it for a daemon
    /// predating the seam; a new supervisor sets both for Claude and this alone
    /// for another agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_bin: Option<String>,
    /// The Codex thread this session is attached to, when the agent is Codex.
    /// Absent for Claude. Opaque — carried for identity, never parsed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codex_thread_id: Option<String>,
    /// The runtime socket the Codex broker exposes to ccd. Absent for Claude.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codex_socket: Option<String>,
    /// The monotonic thread **generation** (visit) this registration speaks for
    /// (D4). The daemon adopts a registration only when this is not older than a
    /// generation it already holds, so a stale supervisor frame can never
    /// overwrite newer adapter state. Absent for Claude, whose sessions have no
    /// generations, which is why the guard is inert on the Claude path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codex_generation: Option<u64>,
    pub started_at: String,
    /// What this supervisor is able to honour, as [`crate::PROTOCOL_MINOR`].
    ///
    /// Defaults to `0` for a supervisor left over from an in-place upgrade, and
    /// that default is load-bearing rather than cosmetic: a supervisor below
    /// minor 3 silently ignores [`SupervisorRequest::SendText::expect`], so the
    /// daemon cannot bind an approval to the prompt it was created for. Remote
    /// actuation of a permission prompt is refused in that case rather than
    /// performed against an unproven screen.
    #[serde(default)]
    pub protocol_minor: u32,
    /// **This is a corpse's replay, not a supervisor introducing a run it hosts.**
    ///
    /// `report_exit` opens a *fresh* connection and replays this very frame
    /// immediately before [`ClientFrame::SessionExited`], so that a session which
    /// started *and* ended while `ccd` was down still has a row for its end to be
    /// recorded against. The replay is byte-identical to the original
    /// registration — it *is* the original registration, re-sent — and that is
    /// precisely the problem this flag solves: nothing else in the frame tells
    /// the daemon that the process behind it is already dead.
    ///
    /// Without it a replay is indistinguishable from a live supervisor arriving,
    /// so it takes the session over. When another supervisor has meanwhile
    /// resumed the same uid, that hand-over is a lie in both directions: the
    /// replay overwrites the newer run's row, and the exit that follows is then
    /// established against an identity the replay itself just minted — so the
    /// daemon ends the run that *replaced* the one that died.
    ///
    /// Set only by `report_exit`. Absent — an older supervisor, or any other
    /// client — decodes `false`, which is exactly the behaviour that shipped:
    /// nothing negotiates on this, and no peer has to understand it.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub exit_replay: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SupervisorRequest {
    /// Type into the session's TTY, but only once the expected prompt is
    /// confirmed on screen. This is the mirror model's answer path: phone input
    /// becomes literal keyboard input, so first-answer-wins is physical.
    SendText {
        text: String,
        require: PromptPresence,
        /// How to recognise a prompt that is *asking* something, when the
        /// operator has configured that themselves.
        ///
        /// Recovery never sends `Escape` at a screen matching this: a slash
        /// command can be a skill, a skill can reach a tool, and cancelling a
        /// decision nobody made is worse than leaving a view standing. `None`
        /// means the operator has configured nothing, and the supervisor uses
        /// the question itself — deliberately narrower than the default
        /// permission needles, which include `esctocancel`, a hint Claude's
        /// *views* also offer and which would therefore stop the rescue this
        /// postcondition exists for.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        asking: Option<PromptPresence>,
        /// Whether `require` names Claude's **composer**, as opposed to a
        /// prompt awaiting an answer.
        ///
        /// Carried rather than inferred from `require`'s variant, because a
        /// configured `input_box_needles` override arrives as `AnyOf` and the
        /// variant then says nothing. The supervisor needs the distinction
        /// twice: a composer must have the keyboard before anything is typed
        /// into it, and a prompt legitimately does not. Absent from a
        /// pre-minor-9 daemon, where it defaults false and the keyboard check
        /// simply does not run — the behaviour that shipped.
        #[serde(default)]
        targets_composer: bool,
        /// Send Enter after the text. False lets the phone stage a draft.
        #[serde(default = "default_true")]
        submit: bool,
        /// The prompt this text is an answer to, as it looked when the card was
        /// created. Re-checked by the supervisor in the same breath as the
        /// presence check — the only place where "the prompt is there" and "the
        /// keys are sent" are close enough together for the answer to be about
        /// the prompt a human actually saw.
        ///
        /// `None` for a free-text takeover into the composer, which is not an
        /// answer to any prompt and whose interlock is composer presence.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        expect: Option<PromptFingerprint>,
        /// Run the post-injection composer check. Set for word-shaped slash
        /// commands only: ordinary prose cannot open a view, and paying two
        /// captures plus a settling wait on every message would tax the
        /// common path for a case that cannot arise on it.
        #[serde(default)]
        recover_composer: bool,
        /// Keep the pane captured while the view was up. Decided by the
        /// daemon against its own allowlist rather than trusted from the
        /// phone, and only ever set for the three snapshot commands —
        /// otherwise this quietly becomes the generic TUI bridge that was
        /// rejected by design.
        #[serde(default)]
        capture_recovered: bool,
        /// Complete the view this command opened instead of dismissing it,
        /// and the single needle that must be on screen first.
        ///
        /// Built by the daemon from the command it is about to complete, never
        /// taken from the phone. This is the one place a keystroke *commits*
        /// something, so the screen has to show the **selected** affirmative
        /// row, for the value that was asked for — a screen that merely holds
        /// still is not authorisation, and neither is one that merely contains
        /// the words somewhere.
        ///
        /// `None` is the ordinary rescue: `Escape`, and no such demand. A
        /// needle that cannot be established is also the ordinary rescue —
        /// never a key withheld with the view left open.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        confirm_view: Option<String>,
        /// When the daemon stops listening for this request's answer, as a
        /// millisecond on the host's **monotonic** clock
        /// ([`crate::time::now_monotonic_ms`]) — one clock for every process
        /// on the machine, immune to wall-time steps that would otherwise
        /// grant a queued request more time than its sender will wait. The
        /// supervisor budgets every deliberate wait against it, so an
        /// answer computed is an answer delivered. Absent from an older
        /// daemon; the supervisor then derives a budget from its own
        /// config. (Minor 12.)
        #[serde(default, skip_serializing_if = "Option::is_none")]
        respond_by_monotonic_ms: Option<u64>,
    },
    /// Text snapshot of the pane. Presence checks and mirroring only. The
    /// composer is read as a shape — the rows of its box, and nothing else
    /// about them (see [`composer_is_drawn`]); everything else is matched
    /// against needles. The one place a needle carries meaning rather than
    /// mere presence is recovery's "is this screen asking something" guard;
    /// see `SendText::asking`.
    Capture {
        #[serde(default = "default_capture_lines")]
        lines: u32,
        /// Capture the **visible** pane and no scrollback, whatever `lines`
        /// says. Every presence and identity decision uses this: a prompt that
        /// has scrolled off the screen is history, and history must never
        /// authorise a keystroke.
        #[serde(default)]
        visible_only: bool,
    },
    Ping,
}

fn default_true() -> bool {
    true
}

fn default_capture_lines() -> u32 {
    80
}

/// Proof that the prompt now on screen is the one an approval was created for.
///
/// Not a hash of the whole pane: a pane carries a cursor, a spinner and elapsed
/// counters, so a whole-pane hash would refuse every answer. It covers the
/// prompt *block* — the line the presence needle matched, a bounded run of the
/// lines above it (the command being asked about) and everything below it (the
/// option list and its footer) — which is exactly the region that is static for
/// as long as one prompt is up and different for the next one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PromptFingerprint {
    /// The normalised needle that located the block, carried so the checker
    /// extracts the same region rather than guessing at one.
    pub needle: String,
    /// sha256 of the normalised block.
    pub sha: String,
}

/// Lines above the matched needle folded into a prompt's identity.
///
/// Bounded rather than unbounded: everything above the prompt is streamed agent
/// output, and hashing an arbitrary amount of it would make the fingerprint
/// depend on how much scrolled past rather than on which prompt is showing.
const PROMPT_CONTEXT_LINES: usize = 12;

/// The prompt block a fingerprint covers, normalised, or `None` when the pane
/// does not contain the needle on any single line.
///
/// `None` is a refusal, not an absence: it means the identity of what is on
/// screen could not be established, and the caller must fail toward the human.
pub fn prompt_block(pane_text: &str, needle: &str) -> Option<String> {
    let needle = normalize_for_match(needle);
    if needle.is_empty() {
        return None;
    }
    let lines: Vec<&str> = pane_text.lines().collect();
    // The *last* match, not the first: if one visible pane somehow shows the
    // wording twice, the live prompt is the lower one.
    let anchor = lines
        .iter()
        .rposition(|line| normalize_for_match(line).contains(&needle))?;
    let start = anchor.saturating_sub(PROMPT_CONTEXT_LINES);
    let mut block: Vec<String> = lines[start..]
        .iter()
        .map(|line| normalize_for_match(line))
        .collect();
    // Trailing blank lines are padding, and how many of them there are depends
    // on the pane height rather than on the prompt.
    while block.last().is_some_and(|line| line.is_empty()) {
        block.pop();
    }
    if block.is_empty() {
        return None;
    }
    Some(block.join("\n"))
}

/// Fingerprint the prompt a needle matched, or `None` if it cannot be located.
pub fn prompt_fingerprint(pane_text: &str, needle: &str) -> Option<PromptFingerprint> {
    let block = prompt_block(pane_text, needle)?;
    Some(PromptFingerprint {
        needle: normalize_for_match(needle),
        sha: crate::hash::sha256_hex(block.as_bytes()),
    })
}

impl PromptFingerprint {
    /// Is the prompt this was taken from still the one on screen?
    pub fn still_on_screen(&self, pane_text: &str) -> bool {
        match prompt_block(pane_text, &self.needle) {
            Some(block) => crate::hash::sha256_hex(block.as_bytes()) == self.sha,
            // Cannot locate the block at all: not a match, and never a pass.
            None => false,
        }
    }
}

/// What must be visible in `capture-pane` output before keys are injected.
///
/// Matching is whitespace-insensitive: Claude's renderer pads with box-drawing
/// glyphs and inconsistent spacing, and the raw render stream contains zero
/// 0x20 bytes at all, so any space-sensitive needle is a latent flake.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "mode", rename_all = "snake_case")]
pub enum PromptPresence {
    /// The composer is accepting input. Judged on the box Claude draws it in
    /// rather than on any needle — see [`composer_is_drawn`] — unless the
    /// operator has configured needles, which arrive as `AnyOf`.
    InputBox,
    /// A permission prompt is on screen ("Do you want to proceed?").
    PermissionPrompt,
    /// Caller-supplied needles; any one matching is enough.
    AnyOf { needles: Vec<String> },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum SupervisorResult {
    /// Keys were injected; `matched` is what authorised it — the needle that
    /// matched, or `"composer"` where the composer was recognised by its shape.
    Sent {
        matched: String,
    },
    /// Keys were injected, Claude's composer disappeared afterwards, and one
    /// `Escape` brought it back.
    ///
    /// Named for the observable fact rather than for whatever appeared: the
    /// supervisor never identifies what opened, so "a view opened" is not a
    /// claim it can make. (It does read the pane for one thing — whether the
    /// screen is asking a question — because that is the one state it must
    /// not send a key into.) What it can prove is that the composer went
    /// away and came back. Measured need: `/status` and its kind replace the
    /// composer, and while it is gone the presence interlock refuses every
    /// further send — the phone is locked out of its own session until
    /// somebody presses Esc at the Mac.
    ComposerRecovered {
        matched: String,
        /// The pane as it looked while the composer was gone — only when
        /// the daemon asked for it, which it does for the three snapshot
        /// commands and nothing else.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pane_snapshot: Option<String>,
        captured_at: String,
    },
    /// The keys landed, the view this command opened was still exactly the
    /// frame that appeared, one `Enter` completed it, and the composer came
    /// back. What the command then *did* is not claimed here — the transcript
    /// receipt says that, and only that.
    ViewConfirmed {
        matched: String,
    },
    /// Typing happened; what followed could not be observed. A capture that
    /// failed, an `Escape` that could not be sent, or a permission prompt on
    /// screen — which is deliberately never Escaped, because a slash command
    /// can be a skill, a skill can reach a tool, and cancelling a decision
    /// nobody made is worse than leaving it standing.
    ///
    /// Distinct from `ComposerLost` because that one is a *claim*: Escape went
    /// out and the composer did not return. This one claims nothing, and the
    /// daemon turns it into `indeterminate` — the status the phone already
    /// reads as "typed, outcome unknown; retry is recognised".
    RecoveryUnconfirmed {
        matched: String,
        reason: String,
    },
    /// The composer went away and one `Escape` did not bring it back.
    /// Measured on `/config`, and on `/keybindings`, which spawns an editor
    /// where Escape is a mode key. Typing happened; this needs a human at
    /// the Mac, and no further keys are guessed at.
    ComposerLost {
        matched: String,
    },
    /// Presence check failed. Nothing was typed.
    Refused {
        reason: String,
    },
    Snapshot {
        text: String,
    },
    Pong,
    Error {
        message: String,
    },
}

/// Strip *all* whitespace and lowercase, for prompt-presence matching.
pub fn normalize_for_match(s: &str) -> String {
    s.chars()
        .filter(|c| !c.is_whitespace())
        .flat_map(|c| c.to_lowercase())
        .collect()
}

/// The box-drawing horizontals a composer rule may be made of. Claude draws
/// `─` (U+2500); the heavier weights are accepted so a restyle costs the
/// composer one glyph rather than every send in the fleet.
const RULE_GLYPHS: [char; 3] = ['─', '━', '═'];

/// The composer's prompt marker — and the marker Claude puts on the selected
/// row of every menu and permission prompt, which is why finding one settles
/// nothing on its own.
const PROMPT_GLYPH: char = '❯';

/// What authorises a send when the composer is recognised by its shape: a
/// stable token rather than a fragment of Claude's copy, because no text was
/// matched to get here.
const COMPOSER: &str = "composer";

/// A row that is box-drawing horizontals from column zero, and nothing else.
///
/// Length is not part of it. A composer in a three-column pane is ruled with
/// three glyphs and is as typable as one at two hundred, and at that width
/// every footer hint is truncated away, so the rule is the only signal left.
/// Column zero is: the rule Claude draws starts where the pane starts, and an
/// indented one is somebody's output being quoted.
fn is_rule_row(line: &str) -> bool {
    let row = line.trim_end();
    !row.is_empty() && row.chars().all(|c| RULE_GLYPHS.contains(&c))
}

/// A row that opens at column zero with the prompt marker standing alone:
/// what follows it is the no-break space Claude pads the caret with, an
/// ordinary space, or nothing at all.
fn is_prompt_row(line: &str) -> bool {
    let mut chars = line.chars();
    chars.next() == Some(PROMPT_GLYPH) && chars.next().is_none_or(char::is_whitespace)
}

/// Is Claude's composer drawn on this pane?
///
/// **The shape is the signal and the footer copy is not.** `? for shortcuts`
/// is dropped the moment the shift+tab mode hint needs the room, and
/// `← for agents` is rewritten to `← 1 agent` as soon as one subagent exists,
/// so a session that types perfectly well can show neither string. What it
/// always shows is the box: a rule the width of the pane, the prompt row, a
/// closing rule, the footer.
///
/// The rule has to be the row *immediately above*, and both rows have to open
/// at column zero. A closing rule cannot stand in for the opening one —
/// prompt text wraps, and every continuation row pushes the closing rule
/// further away, so the row above is the only row the box is reliably at. The
/// marker alone cannot be enough either: `❯` opens the transcript echo of
/// every submitted prompt and marks the highlighted row of every menu. And an
/// *indented* pair is a quotation — agents print captured panes into their own
/// output, and Claude indents tool results — so a composer that has been
/// written about is not a composer that is there.
///
/// A prompt row on the pane's first line therefore reads as no composer, which
/// is the direction to fail in: that is also what a shell that just printed a
/// `❯` looks like, and what a transcript scrolled to an echoed prompt looks
/// like. A composer holding more text than the pane is tall loses its top rule
/// off the screen and is refused with them.
///
/// What survives is a pane that puts a rule at column zero directly above a
/// column-zero `❯` while the composer is not the thing with the keyboard — a
/// textual collision no reading of the text can rule out. The cursor is what
/// stands behind it: see `authorise` in the supervisor, which asks tmux who
/// holds the keyboard before anything is typed.
pub fn composer_is_drawn(pane_text: &str) -> bool {
    let mut above = "";
    for row in pane_text.lines() {
        if is_prompt_row(row) && is_rule_row(above) {
            return true;
        }
        above = row;
    }
    false
}

impl PromptPresence {
    /// Default needles per mode. Kept here (not in the daemon) so the shim and
    /// the daemon can never drift, and overridable from config because Claude's
    /// TUI copy is the single most churn-prone surface we depend on.
    ///
    /// The composer has none: it is recognised by [`composer_is_drawn`], and an
    /// operator who configures `input_box_needles` gets an `AnyOf` carrying
    /// theirs instead of this variant.
    pub fn default_needles(&self) -> Vec<String> {
        match self {
            PromptPresence::InputBox => Vec::new(),
            PromptPresence::PermissionPrompt => {
                vec!["doyouwanttoproceed".to_string(), "esctocancel".to_string()]
            }
            PromptPresence::AnyOf { needles } => {
                needles.iter().map(|n| normalize_for_match(n)).collect()
            }
        }
    }

    /// What this check looks for, in the words a refusal has to use to stay
    /// true — the composer's shape is not a needle and cannot be printed as
    /// one.
    pub fn requirement(&self) -> String {
        match self {
            PromptPresence::InputBox => {
                "the composer's ❯ prompt row under its box rule".to_string()
            }
            other => format!("{:?}", other.default_needles()),
        }
    }

    /// What authorised the send: the needle that matched, or `"composer"` where
    /// the composer was recognised by its shape and no text was matched at all.
    pub fn find_match(&self, pane_text: &str, overrides: Option<&[String]>) -> Option<String> {
        let needles: Vec<String> = match overrides {
            Some(list) if !list.is_empty() => list.iter().map(|n| normalize_for_match(n)).collect(),
            // Nothing configured, so the composer is judged on its shape.
            // An override is still honoured above: it is the one place an
            // operator can teach this check a screen it cannot see.
            _ if matches!(self, PromptPresence::InputBox) => {
                return composer_is_drawn(pane_text).then(|| COMPOSER.to_string());
            }
            _ => self.default_needles(),
        };
        let haystack = normalize_for_match(pane_text);
        needles
            .into_iter()
            .find(|needle| !needle.is_empty() && haystack.contains(needle.as_str()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A supervisor predating the agent seam sends no `agent`; a daemon must
    /// read it as Claude and never fail. A new supervisor's Codex fields must
    /// round-trip, and an old daemon (which ignores unknown keys) still decodes
    /// the frame to a Claude-shaped registration.
    #[test]
    fn a_registration_without_an_agent_is_claude() {
        use crate::agent::AgentKind;
        let legacy: RegisterSession = serde_json::from_str(
            r#"{"session_id":"cc-1","tmux_session":"cc-1","tmux_socket":"codeconnect",
                "cwd":"/tmp","supervisor_pid":42,"started_at":"t"}"#,
        )
        .expect("a pre-seam registration still decodes");
        assert_eq!(legacy.agent, AgentKind::Claude);
        assert_eq!(legacy.agent_bin, None);
        assert_eq!(legacy.codex_thread_id, None);
        assert_eq!(legacy.codex_generation, None);

        let codex = RegisterSession {
            agent: AgentKind::Codex,
            agent_bin: Some("/opt/codex".into()),
            codex_thread_id: Some("th_1".into()),
            codex_socket: Some("/run/ccd.sock".into()),
            codex_generation: Some(3),
            ..legacy
        };
        let s = serde_json::to_string(&codex).unwrap();
        assert!(s.contains(r#""agent":"codex""#), "{s}");
        assert_eq!(serde_json::from_str::<RegisterSession>(&s).unwrap(), codex);
    }

    /// The pre-`Register` negotiation pair round-trips, and an absent agent in a
    /// query is Claude — the agent every daemon supports.
    #[test]
    fn support_negotiation_frames_round_trip() {
        use crate::agent::AgentKind;
        let query = ClientFrame::NegotiateSupport {
            agent: AgentKind::Codex,
            agent_version: Some("0.147.0".into()),
        };
        let s = serde_json::to_string(&query).unwrap();
        assert!(s.contains(r#""type":"negotiate_support""#), "{s}");
        match serde_json::from_str::<ClientFrame>(&s).unwrap() {
            ClientFrame::NegotiateSupport {
                agent,
                agent_version,
            } => {
                assert_eq!(agent, AgentKind::Codex);
                assert_eq!(agent_version.as_deref(), Some("0.147.0"));
            }
            other => panic!("wrong frame: {other:?}"),
        }
        // Absent agent in a query decodes as Claude.
        let bare: ClientFrame = serde_json::from_str(r#"{"type":"negotiate_support"}"#).unwrap();
        assert!(matches!(
            bare,
            ClientFrame::NegotiateSupport {
                agent: AgentKind::Claude,
                ..
            }
        ));

        let reply = DaemonFrame::SupportedAgents {
            supported_agents: vec![AgentKind::Claude],
            supported: false,
        };
        let s = serde_json::to_string(&reply).unwrap();
        assert!(s.contains(r#""type":"supported_agents""#), "{s}");
        let _: DaemonFrame = serde_json::from_str(&s).unwrap();
    }

    /// Every pane in `fixtures/panes/composer/`: real `capture-pane -p -J`
    /// output from sessions that were taking keys, across every permission
    /// mode, mid-turn, with prompt text typed, wrapped over three rows, and at
    /// three columns wide. Named one by one so a deleted capture is a compile
    /// error rather than a quietly smaller corpus.
    const COMPOSER_PANES: [(&str, &str); 10] = [
        (
            "accept-edits",
            include_str!("../../../fixtures/panes/composer/accept-edits.txt"),
        ),
        (
            "auto-mode",
            include_str!("../../../fixtures/panes/composer/auto-mode.txt"),
        ),
        (
            "bypass-agent-count",
            include_str!("../../../fixtures/panes/composer/bypass-agent-count.txt"),
        ),
        (
            "bypass-placeholder",
            include_str!("../../../fixtures/panes/composer/bypass-placeholder.txt"),
        ),
        (
            "manual-shortcuts",
            include_str!("../../../fixtures/panes/composer/manual-shortcuts.txt"),
        ),
        (
            "mid-turn",
            include_str!("../../../fixtures/panes/composer/mid-turn.txt"),
        ),
        (
            "narrow-3col",
            include_str!("../../../fixtures/panes/composer/narrow-3col.txt"),
        ),
        (
            "transcript-echo",
            include_str!("../../../fixtures/panes/composer/transcript-echo.txt"),
        ),
        (
            "typed-prompt-glyph",
            include_str!("../../../fixtures/panes/composer/typed-prompt-glyph.txt"),
        ),
        (
            "wrapped-multiline",
            include_str!("../../../fixtures/panes/composer/wrapped-multiline.txt"),
        ),
    ];

    /// Every pane in `fixtures/panes/no-composer/`: real captures of screens
    /// with no composer to type into. Every one of them carries a `❯`
    /// somewhere, and that is why they are here.
    const NO_COMPOSER_PANES: [(&str, &str); 6] = [
        (
            "model-menu",
            include_str!("../../../fixtures/panes/no-composer/model-menu.txt"),
        ),
        (
            "permission-prompt",
            include_str!("../../../fixtures/panes/no-composer/permission-prompt.txt"),
        ),
        (
            "plain-shell",
            include_str!("../../../fixtures/panes/no-composer/plain-shell.txt"),
        ),
        (
            "rewind-menu",
            include_str!("../../../fixtures/panes/no-composer/rewind-menu.txt"),
        ),
        (
            "status-view",
            include_str!("../../../fixtures/panes/no-composer/status-view.txt"),
        ),
        (
            "trust-dialog",
            include_str!("../../../fixtures/panes/no-composer/trust-dialog.txt"),
        ),
    ];

    /// Verbatim from `tmux capture-pane -p -J` against a live permission
    /// prompt on claude 2.1.232.
    const PERMISSION_PANE: &str =
        include_str!("../../../fixtures/panes/no-composer/permission-prompt.txt");

    /// A composer with nothing typed into it, manual mode, one subagent.
    const IDLE_PANE: &str = include_str!("../../../fixtures/panes/composer/manual-shortcuts.txt");

    #[test]
    fn every_captured_composer_authorises_a_send() {
        for (name, pane) in COMPOSER_PANES {
            assert_eq!(
                PromptPresence::InputBox.find_match(pane, None).as_deref(),
                Some("composer"),
                "{name} is a live composer and must be typable"
            );
        }
    }

    #[test]
    fn every_captured_pane_without_a_composer_is_refused() {
        for (name, pane) in NO_COMPOSER_PANES {
            assert!(
                PromptPresence::InputBox.find_match(pane, None).is_none(),
                "{name} has no composer to type into"
            );
        }
    }

    /// The footer a live session shows once a subagent exists: the shift+tab
    /// cycle hint takes the room `? for shortcuts` had, and the agent list
    /// counts instead of inviting. Neither hint string is anywhere on the pane
    /// — asserted, because that is what makes it a composer no needle can find
    /// — and it is a composer all the same.
    #[test]
    fn a_composer_whose_footer_offers_no_hint_text_is_still_a_composer() {
        const PANE: &str = include_str!("../../../fixtures/panes/composer/bypass-agent-count.txt");
        assert!(!PANE.contains("for shortcuts"), "no shortcuts hint here");
        assert!(
            !PANE.contains("for agents"),
            "the agent list counts instead"
        );
        assert_eq!(
            PromptPresence::InputBox.find_match(PANE, None).as_deref(),
            Some("composer")
        );
    }

    /// A marker on its own authorises nothing, on the screens that really
    /// offer one.
    ///
    /// `❯` is Claude's selection marker as much as its prompt marker: it
    /// stands on `1. Yes` in the permission prompt, on the highlighted row of
    /// the model menu, on `(current)` in the rewind menu, on the answer the
    /// trust dialog wants — and a shell prints one wherever it is told to.
    /// Every no-composer capture carries one, asserted here so the refusals
    /// below are about the marker being unaccompanied rather than about the
    /// panes being empty.
    #[test]
    fn a_prompt_marker_without_a_rule_over_it_authorises_nothing() {
        for (name, pane) in NO_COMPOSER_PANES {
            assert!(
                pane.contains(PROMPT_GLYPH),
                "{name} must offer a marker, or it proves nothing here"
            );
            assert!(
                PromptPresence::InputBox.find_match(pane, None).is_none(),
                "{name} offers a marker and no composer"
            );
        }
    }

    /// A composer somebody wrote *about* is not a composer that is there.
    ///
    /// Agents print captured panes into their own output and Claude indents
    /// tool results, so a quoted box arrives on screen indented — under, in
    /// this frame, a model menu that owns the keyboard and a marker of its
    /// own. Column zero is what tells the two apart.
    #[test]
    fn a_quoted_composer_in_an_agents_output_authorises_nothing() {
        const QUOTED: &str = "\
⏺ Bash(cat fixtures/panes/composer/narrow-3col.txt)
  ⎿
     ───
     ❯
     ───

  Select model
    1. Default (recommended)
  ❯ 2. Opus";
        assert!(
            QUOTED.contains("───\n     ❯"),
            "the quoted box has to be in there, or this proves nothing"
        );
        assert!(PromptPresence::InputBox.find_match(QUOTED, None).is_none());
    }

    /// A composer in a pane too short to hold its own box: the opening rule is
    /// clipped away, the prompt row is at the top, and the closing rule sits
    /// directly below it.
    ///
    /// This is the pane that separates "the rule above" from "a rule anywhere
    /// next to it". A closing rule is not evidence — it is where the box ends,
    /// and prompt text wraps, so on any composer holding more than one line it
    /// is rows away from the marker. The row above is where the box opens, and
    /// it is the only row that answers.
    #[test]
    fn a_closing_rule_below_the_prompt_row_is_not_a_composer() {
        const PANE: &str =
            include_str!("../../../fixtures/panes/bounds/short-pane-top-rule-clipped.txt");
        let mut rows = PANE.lines();
        assert!(
            is_prompt_row(rows.next().unwrap_or_default()),
            "the prompt row is the top row of the capture"
        );
        assert!(
            is_rule_row(rows.next().unwrap_or_default()),
            "and a rule sits directly below it"
        );
        assert!(PromptPresence::InputBox.find_match(PANE, None).is_none());
    }

    /// A composer holding more text than its pane is tall: the top rule has
    /// scrolled off, so the prompt row is the first row on screen with nothing
    /// above it to stand on, and the send is refused.
    ///
    /// Refusal is the direction to fail in, and this pane is the reason to
    /// leave it that way. A first row beginning with the marker is also what a
    /// shell that printed a `❯` looks like and what a transcript scrolled to
    /// an echoed prompt looks like, so authorising row 0 on its own would type
    /// into both. The footer offers no hint text at this size either, so there
    /// is nothing else on the pane that says composer.
    #[test]
    fn a_composer_taller_than_its_pane_has_no_rule_to_stand_on() {
        const PANE: &str =
            include_str!("../../../fixtures/panes/bounds/tall-composer-top-rule-offscreen.txt");
        assert!(
            PANE.starts_with(PROMPT_GLYPH),
            "the prompt row is the top row of the capture"
        );
        assert!(!PANE.contains("for shortcuts") && !PANE.contains("for agents"));
        assert!(PromptPresence::InputBox.find_match(PANE, None).is_none());
    }

    /// The operator's escape hatch, on both routes it arrives by: handed to
    /// `find_match` directly, and — the way the daemon does it — as the
    /// `AnyOf` that replaces the variant outright.
    #[test]
    fn configured_needles_still_decide_the_composer() {
        let literal = ["⏸ manual mode on".to_string()];
        assert_eq!(
            PromptPresence::InputBox
                .find_match(IDLE_PANE, Some(&literal))
                .as_deref(),
            Some("⏸manualmodeon")
        );
        assert!(PromptPresence::InputBox
            .find_match(IDLE_PANE, Some(&["not on this screen".to_string()]))
            .is_none());
        assert_eq!(
            PromptPresence::AnyOf {
                needles: vec!["⏸ manual mode on".to_string()]
            }
            .find_match(IDLE_PANE, None)
            .as_deref(),
            Some("⏸manualmodeon")
        );
        assert!(PromptPresence::AnyOf {
            needles: vec!["not on this screen".to_string()]
        }
        .find_match(IDLE_PANE, None)
        .is_none());
    }

    #[test]
    fn permission_prompt_detected_on_real_pane() {
        let m = PromptPresence::PermissionPrompt
            .find_match(PERMISSION_PANE, None)
            .expect("must detect the live permission prompt");
        assert_eq!(m, "doyouwanttoproceed");
    }

    #[test]
    fn permission_prompt_not_detected_on_idle_pane() {
        assert!(PromptPresence::PermissionPrompt
            .find_match(IDLE_PANE, None)
            .is_none());
    }

    #[test]
    fn input_box_detected_on_idle_pane() {
        assert!(PromptPresence::InputBox
            .find_match(IDLE_PANE, None)
            .is_some());
    }

    #[test]
    fn matching_survives_reflow_and_padding() {
        // Same words, different wrapping and spacing: must still match.
        let reflowed = "Do  you\n want to\tproceed?";
        assert!(PromptPresence::PermissionPrompt
            .find_match(reflowed, None)
            .is_some());
    }

    #[test]
    fn overrides_replace_defaults() {
        let m = PromptPresence::PermissionPrompt
            .find_match(PERMISSION_PANE, Some(&["Create empty file".to_string()]))
            .unwrap();
        assert_eq!(m, "createemptyfile");
        assert!(PromptPresence::PermissionPrompt
            .find_match(PERMISSION_PANE, Some(&["nothing here".to_string()]))
            .is_none());
    }

    #[test]
    fn a_dismissed_prompt_is_told_apart_from_a_pane_we_cannot_read() {
        // The local-resolution rule is "prompt gone AND composer back". These
        // are the three panes it has to tell apart, and the middle one is the
        // false positive that a bare absence check would trip on.
        let answered = |pane: &str| {
            PromptPresence::PermissionPrompt
                .find_match(pane, None)
                .is_none()
                && PromptPresence::InputBox.find_match(pane, None).is_some()
        };
        assert!(!answered(PERMISSION_PANE), "the prompt is still up");
        assert!(
            !answered("some other tmux window entirely\n$ ls"),
            "a switched-away pane has no prompt either, and must not read as answered"
        );
        assert!(!answered(""), "an empty capture proves nothing");
        assert!(answered(IDLE_PANE), "prompt gone and the composer is back");
    }

    #[test]
    fn empty_needles_never_match_everything() {
        assert!(PromptPresence::AnyOf {
            needles: vec![String::new()]
        }
        .find_match(PERMISSION_PANE, None)
        .is_none());
    }

    #[test]
    fn frames_round_trip() {
        let frame = ClientFrame::Hook(HookPost {
            session_id: "cc-1".into(),
            session_uid: Some("01K1B3XQ8ZC0DE5FGH7JKMNPQR".into()),
            event: "PermissionRequest".into(),
            payload: serde_json::json!({"tool_name": "Bash"}),
            wait: true,
        });
        let line = serde_json::to_string(&frame).unwrap();
        assert!(line.contains("\"type\":\"hook\""));
        let back: ClientFrame = serde_json::from_str(&line).unwrap();
        match back {
            ClientFrame::Hook(post) => {
                assert_eq!(post.session_id, "cc-1");
                assert_eq!(
                    post.session_uid.as_deref(),
                    Some("01K1B3XQ8ZC0DE5FGH7JKMNPQR")
                );
                assert!(post.wait);
            }
            other => panic!("wrong frame: {other:?}"),
        }
    }

    #[test]
    fn a_hook_or_registration_from_an_older_build_still_decodes() {
        // The in-place upgrade case, which is not hypothetical: a session
        // running when the daemon is upgraded keeps posting from the settings
        // file it was started with, and its supervisor is the old binary.
        let post: ClientFrame = serde_json::from_str(
            r#"{"type":"hook","session_id":"cc-1","event":"PreToolUse","payload":{}}"#,
        )
        .unwrap();
        match post {
            ClientFrame::Hook(post) => assert_eq!(post.session_uid, None),
            other => panic!("wrong frame: {other:?}"),
        }

        let register: ClientFrame = serde_json::from_str(
            r#"{"type":"register","session_id":"cc-1","tmux_session":"cc-1",
                "tmux_socket":"codeconnect","cwd":"/tmp","supervisor_pid":42,
                "started_at":"t"}"#,
        )
        .unwrap();
        match register {
            ClientFrame::Register(info) => {
                assert_eq!(info.session_uid, None);
                assert_eq!(
                    info.protocol_minor, 0,
                    "a supervisor that does not say what it can honour must be \
                     assumed to honour nothing added since"
                );
            }
            other => panic!("wrong frame: {other:?}"),
        }
    }

    // -------------------------------------------------------- prompt identity

    /// The same permission prompt, one command later: same wording, same
    /// options, same footer, a different file.
    fn second_permission_pane() -> String {
        PERMISSION_PANE.replace("ccprobe_x", "ccprobe_d")
    }

    #[test]
    fn a_fingerprint_matches_its_own_prompt_and_no_other() {
        let taken = prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed")
            .expect("the live prompt must be fingerprintable");
        assert!(taken.still_on_screen(PERMISSION_PANE));
        // The failure this guards against: a *different* prompt, same wording,
        // same options. Answering it with the previous card would type into it.
        assert!(
            !taken.still_on_screen(&second_permission_pane()),
            "two different prompts must not share an identity"
        );
        // And a pane with no prompt at all proves nothing, so it never passes.
        assert!(!taken.still_on_screen(IDLE_PANE));
        assert!(!taken.still_on_screen(""));
    }

    #[test]
    fn a_fingerprint_survives_the_reflow_a_real_pane_does() {
        // The pane is re-rendered constantly; what must not change is the
        // prompt block itself. Padding and case are normalised away.
        let taken = prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed").unwrap();
        let repadded = PERMISSION_PANE.replace("   ", "     ").replace('?', "?  ");
        assert!(
            taken.still_on_screen(&repadded),
            "whitespace churn must not read as a different prompt"
        );
    }

    #[test]
    fn a_moved_selection_is_not_the_same_prompt() {
        // The operator arrowed down to "No" while the phone was deciding.
        // Refusing is correct: whoever is at the keyboard owns this prompt.
        let taken = prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed").unwrap();
        let moved = PERMISSION_PANE
            .replace(" ❯ 1. Yes", "   1. Yes")
            .replace("   2. No", " ❯ 2. No");
        assert!(!taken.still_on_screen(&moved));
    }

    #[test]
    fn a_prompt_that_cannot_be_located_yields_no_fingerprint() {
        assert!(prompt_fingerprint(IDLE_PANE, "doyouwanttoproceed").is_none());
        assert!(prompt_fingerprint(PERMISSION_PANE, "").is_none());
        assert!(prompt_fingerprint("", "doyouwanttoproceed").is_none());
    }

    #[test]
    fn a_fingerprint_round_trips_over_the_socket() {
        let request = SupervisorRequest::SendText {
            text: "1".into(),
            require: PromptPresence::PermissionPrompt,
            asking: None,
            targets_composer: false,
            submit: true,
            expect: prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed"),
            recover_composer: false,
            capture_recovered: false,
            confirm_view: None,
            respond_by_monotonic_ms: None,
        };
        let line = serde_json::to_string(&request).unwrap();
        assert!(line.contains("\"expect\""), "{line}");
        match serde_json::from_str::<SupervisorRequest>(&line).unwrap() {
            SupervisorRequest::SendText { expect, .. } => {
                assert!(expect.unwrap().still_on_screen(PERMISSION_PANE));
            }
            other => panic!("wrong request: {other:?}"),
        }
    }

    /// The recovery fields are additive: a supervisor below minor 9 sends a
    /// frame without them, and a minor-9 daemon must still decode it — as
    /// "no recovery", which is exactly what that supervisor does.
    #[test]
    fn a_pre_minor_nine_send_text_still_decodes() {
        let legacy = r#"{"kind":"send_text","text":"hi","require":{"mode":"input_box"},
                         "submit":true}"#;
        match serde_json::from_str::<SupervisorRequest>(legacy).unwrap() {
            SupervisorRequest::SendText {
                recover_composer,
                capture_recovered,
                ..
            } => {
                assert!(!recover_composer);
                assert!(!capture_recovered);
            }
            other => panic!("wrong request: {other:?}"),
        }
    }

    /// The two new results round-trip, and the snapshot stays optional.
    #[test]
    fn composer_results_round_trip() {
        let recovered = SupervisorResult::ComposerRecovered {
            matched: "foragents".into(),
            pane_snapshot: Some("Model: …".into()),
            captured_at: "2026-08-05T14:32:08Z".into(),
        };
        let line = serde_json::to_string(&recovered).unwrap();
        assert!(line.contains("\"status\":\"composer_recovered\""), "{line}");
        match serde_json::from_str::<SupervisorResult>(&line).unwrap() {
            SupervisorResult::ComposerRecovered { pane_snapshot, .. } => {
                assert_eq!(pane_snapshot.as_deref(), Some("Model: …"));
            }
            other => panic!("wrong result: {other:?}"),
        }
        let lost = serde_json::to_string(&SupervisorResult::ComposerLost {
            matched: "foragents".into(),
        })
        .unwrap();
        assert!(lost.contains("\"status\":\"composer_lost\""), "{lost}");
    }

    #[test]
    fn a_capture_asks_for_the_visible_pane_only_when_it_says_so() {
        // The default stays "with scrollback" so a mirroring snapshot keeps its
        // context; every presence decision opts in explicitly.
        let legacy: SupervisorRequest =
            serde_json::from_str(r#"{"kind":"capture","lines":80}"#).unwrap();
        match legacy {
            SupervisorRequest::Capture { visible_only, .. } => assert!(!visible_only),
            other => panic!("wrong request: {other:?}"),
        }
        let scoped: SupervisorRequest =
            serde_json::from_str(r#"{"kind":"capture","lines":80,"visible_only":true}"#).unwrap();
        match scoped {
            SupervisorRequest::Capture { visible_only, .. } => assert!(visible_only),
            other => panic!("wrong request: {other:?}"),
        }
    }

    #[test]
    fn daemon_info_tells_launchd_apart_from_a_hand_started_process() {
        let mut info = DaemonInfo {
            pid: 4242,
            version: "0.1.0".into(),
            protocol_version: crate::PROTOCOL_VERSION,
            protocol_minor: crate::PROTOCOL_MINOR,
            started_at: "2026-07-31T10:00:00.000Z".into(),
            launchd_label: Some(crate::LAUNCHD_LABEL.to_string()),
            endpoint_host: "host.ts.net".into(),
            bind_ip: Some("100.64.0.7".into()),
            exe_path: Some("/Users/dev/.codeconnect/bin/ccd".into()),
            exe_sha: Some("abc123".into()),
            build_id: Some("227f6d4e1791".into()),
            endpoint_port: 8787,
            tls: true,
            sessions: 2,
        };
        assert!(info.is_launchd_managed());

        // A foreground `ccd &` and a job with somebody else's label are both
        // "not ours to restart", and must not be confused with each other.
        info.launchd_label = None;
        assert!(!info.is_launchd_managed());
        info.launchd_label = Some("com.example.other".into());
        assert!(!info.is_launchd_managed());

        let line = serde_json::to_string(&DaemonFrame::Daemon(info)).unwrap();
        assert!(line.contains("\"type\":\"daemon\""), "{line}");
        let _: DaemonFrame = serde_json::from_str(&line).unwrap();
    }

    #[test]
    fn pairing_frames_round_trip() {
        let request = ClientFrame::CreatePairing {
            ttl_secs: crate::pairing::PAIRING_TTL_SECS,
            allow_ssh: false,
        };
        let line = serde_json::to_string(&request).unwrap();
        assert!(line.contains("\"type\":\"create_pairing\""), "{line}");
        match serde_json::from_str::<ClientFrame>(&line).unwrap() {
            ClientFrame::CreatePairing { ttl_secs, .. } => assert_eq!(ttl_secs, 300),
            other => panic!("wrong frame: {other:?}"),
        }

        let reply = DaemonFrame::Pairing {
            code: "ABCD2345".into(),
            expires_at: "2026-07-31T10:05:00.000Z".into(),
            host: "host.ts.net".into(),
            port: 8787,
            tls: true,
            allow_ssh: AlwaysFalse,
        };
        let line = serde_json::to_string(&reply).unwrap();
        assert!(line.contains("\"type\":\"pairing\""), "{line}");
        let _: DaemonFrame = serde_json::from_str(&line).unwrap();
    }

    #[test]
    fn revoke_names_the_device_to_revoke() {
        let frame: ClientFrame =
            serde_json::from_str(r#"{"type":"revoke_device","device":"iPhone"}"#).unwrap();
        match frame {
            ClientFrame::RevokeDevice { device, ssh_only } => {
                assert_eq!(device, "iPhone");
                assert!(!ssh_only, "a shim that omits the flag is not asking for it");
            }
            other => panic!("wrong frame: {other:?}"),
        }
        assert!(frame_from(r#"{"type":"revoke_device","device":"iPhone"}"#)
            .ssh_refusal()
            .is_none());
    }

    fn frame_from(line: &str) -> ClientFrame {
        serde_json::from_str(line).expect("a frame an older shim can send must still decode")
    }

    #[test]
    fn a_shim_asking_for_an_ssh_key_is_refused_and_told_why() {
        for (line, flag) in [
            (
                r#"{"type":"create_pairing","ttl_secs":300,"allow_ssh":true}"#,
                "--ssh",
            ),
            (
                r#"{"type":"revoke_device","device":"iPhone","ssh_only":true}"#,
                "revoke <device>",
            ),
        ] {
            let refusal = frame_from(line)
                .ssh_refusal()
                .unwrap_or_else(|| panic!("must be refused: {line}"));
            assert!(
                refusal.contains("does not manage SSH keys"),
                "the refusal must say why: {refusal}"
            );
            assert!(
                refusal.contains(flag) && refusal.contains("update the codeconnect CLI"),
                "the refusal must name a way out: {refusal}"
            );
        }
    }

    #[test]
    fn a_flag_that_is_absent_or_false_is_not_a_refusal() {
        for line in [
            r#"{"type":"create_pairing","ttl_secs":300}"#,
            r#"{"type":"create_pairing","ttl_secs":300,"allow_ssh":false}"#,
            r#"{"type":"revoke_device","device":"iPhone"}"#,
            r#"{"type":"revoke_device","device":"iPhone","ssh_only":false}"#,
        ] {
            assert!(
                frame_from(line).ssh_refusal().is_none(),
                "must proceed normally: {line}"
            );
        }
    }

    #[test]
    fn the_reply_frames_still_carry_the_field_an_older_shim_decodes_by() {
        // Serialized as `false` and unsettable: the daemon holds no SSH key to
        // report on, and a shim that cannot find the key at all refuses the
        // whole frame rather than the field.
        let pairing = serde_json::to_string(&DaemonFrame::Pairing {
            code: "ABCD2345".into(),
            expires_at: "2026-07-31T10:05:00.000Z".into(),
            host: "host.ts.net".into(),
            port: 8787,
            tls: true,
            allow_ssh: AlwaysFalse,
        })
        .unwrap();
        assert!(pairing.contains(r#""allow_ssh":false"#), "{pairing}");

        let revoked = serde_json::to_string(&DaemonFrame::Revoked {
            device: crate::pairing::DeviceSummary {
                device_id: "d1".into(),
                name: "iPhone".into(),
                created_at: "2026-07-31T10:00:00.000Z".into(),
                last_seen_at: None,
                revoked_at: Some("2026-07-31T10:05:00.000Z".into()),
            },
            token_revoked: true,
            ssh_key_removed: AlwaysFalse,
        })
        .unwrap();
        assert!(revoked.contains(r#""ssh_key_removed":false"#), "{revoked}");

        // A `true` from an older *daemon* decodes and lands as false, so a
        // current shim never reports a key it cannot have been told about.
        let from_older: DaemonFrame =
            serde_json::from_str(&pairing.replace(r#""allow_ssh":false"#, r#""allow_ssh":true"#))
                .unwrap();
        match from_older {
            DaemonFrame::Pairing { allow_ssh, .. } => assert_eq!(allow_ssh, AlwaysFalse),
            other => panic!("wrong frame: {other:?}"),
        }
    }

    #[test]
    fn send_text_defaults_to_submitting() {
        let req: SupervisorRequest = serde_json::from_str(
            r#"{"kind":"send_text","text":"hi","require":{"mode":"input_box"}}"#,
        )
        .unwrap();
        match req {
            SupervisorRequest::SendText { submit, .. } => assert!(submit),
            other => panic!("wrong request: {other:?}"),
        }
    }
}
