//! Unix-socket frames spoken at `~/.codeconnect/ccd.sock`.
//!
//! Newline-delimited JSON, one frame per line. Two kinds of client connect:
//!
//!   * **cc-hook** — one `Hook` frame, then either exits immediately
//!     (observability) or reads exactly one `HookReply` (gate events).
//!   * **supervisor** — one `Register` frame, then stays connected for the life
//!     of the session. The daemon pushes `SupervisorRequest`s down this socket.
//!
//! The supervisor connects *out* to the daemon, never the reverse. That is what
//! keeps `ccd` out of the agents' process-parent chain, so `kill -9 ccd` cannot
//! take a session with it: the daemon is an observer, and killing an observer
//! must never kill what it was observing.

use serde::{Deserialize, Serialize};

use crate::event::SessionSummary;
use crate::hook::HookDecision;

/// Frames larger than this are a bug or an attack; the reader drops the
/// connection rather than growing its buffer without bound. Tool responses of a
/// few hundred KB are normal, so the ceiling is generous.
pub const MAX_FRAME_BYTES: usize = 8 * 1024 * 1024;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientFrame {
    Hook(HookPost),
    Register(RegisterSession),
    SupervisorResponse {
        id: String,
        result: SupervisorResult,
    },
    Heartbeat {
        session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_uid: Option<String>,
    },
    /// Reported over a *fresh* connection, after the session is already gone, so
    /// it has to carry its own identity — there is no registered socket left to
    /// infer it from, and a bare `cc-1` could by then belong to a new run.
    SessionExited {
        session_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_uid: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        exit_code: Option<i32>,
    },
    ListSessions,
    /// `cc pair`. The daemon mints and stores the code, because it is the only
    /// process that will later be asked to honour it — a code generated by the
    /// shim and handed over would have to survive a daemon restart in a second
    /// place, for no benefit.
    CreatePairing {
        #[serde(default)]
        ttl_secs: u64,
        /// `cc pair --ssh`. Consent to install an SSH key is bound to *this
        /// code*, not to the daemon's configuration, so it expires with the
        /// code and cannot be reused by a later pairing.
        #[serde(default)]
        allow_ssh: bool,
    },
    ListDevices,
    /// `cc revoke <device>` (`ssh_only` for `cc ssh-revoke <device>`).
    RevokeDevice {
        /// A device id, a device id prefix, or an exact name.
        device: String,
        /// Remove the SSH key but leave the device paired.
        #[serde(default)]
        ssh_only: bool,
    },
    /// "Who is answering this socket?" — asked by `cc daemon status` and by
    /// `cc daemon install` before it decides whether it is about to fight a
    /// daemon somebody started by hand.
    ///
    /// Asked over the socket rather than read from a pidfile: a pidfile can
    /// outlive its process and name a pid that now belongs to something else,
    /// and `cc daemon install` uses this answer to send a signal.
    DaemonInfo,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum DaemonFrame {
    HookReply {
        decision: HookDecision,
    },
    Ack,
    Error {
        message: String,
    },
    SupervisorRequest {
        id: String,
        request: SupervisorRequest,
    },
    Sessions {
        sessions: Vec<SessionSummary>,
    },
    /// Everything `cc pair` needs to draw the QR. The host and port come from
    /// the daemon rather than being re-derived by the shim: the daemon already
    /// resolved them to decide what to bind and whether it holds a certificate,
    /// and two independent answers to "where am I reachable" is exactly how a
    /// QR ends up pointing somewhere nothing is listening.
    Pairing {
        code: String,
        expires_at: String,
        host: String,
        port: u16,
        /// True when the daemon serves `wss://`, so the shim can tell the
        /// operator which scheme the phone will use.
        tls: bool,
        allow_ssh: bool,
    },
    Devices {
        devices: Vec<crate::pairing::DeviceSummary>,
    },
    Revoked {
        device: crate::pairing::DeviceSummary,
        /// False when the device was already revoked — reported rather than
        /// treated as an error, so `cc revoke` is idempotent.
        token_revoked: bool,
        ssh_key_removed: bool,
    },
    Daemon(DaemonInfo),
}

/// The daemon's own account of itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DaemonInfo {
    pub pid: u32,
    pub version: String,
    pub protocol_version: u32,
    pub protocol_minor: u32,
    pub started_at: String,
    /// The launchd job this process belongs to, taken from `XPC_SERVICE_NAME`.
    ///
    /// `None` means "started some other way" — a foreground `ccd &`, a debugger,
    /// a test. That distinction is the whole reason this field exists: `getppid()
    /// == 1` is true of any orphan, so it cannot tell a launchd job from a
    /// daemon whose parent shell has exited, and installing the LaunchAgent on
    /// top of the latter would leave two processes fighting over one socket.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub launchd_label: Option<String>,
    /// Where the phone is told to connect, so `cc daemon status` can show it
    /// without re-deriving it and getting a different answer.
    pub endpoint_host: String,
    pub endpoint_port: u16,
    pub tls: bool,
    pub sessions: usize,
}

impl DaemonInfo {
    /// True when launchd, and not a human, is responsible for restarting this
    /// process.
    pub fn is_launchd_managed(&self) -> bool {
        self.launchd_label.as_deref() == Some(crate::LAUNCHD_LABEL)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookPost {
    /// CodeConnect session name (`cc-1`), resolved by cc-hook from its
    /// `--session` argument or `CODECONNECT_SESSION`.
    pub session_id: String,
    /// The run's unique identity, from `--session-uid` or
    /// `CODECONNECT_SESSION_UID`.
    ///
    /// Absent for a session started before this existed (its generated settings
    /// file predates the flag) and for a session CodeConnect did not launch at
    /// all. The daemon then resolves the name to the newest live run, or adopts
    /// a fresh identity — so a missing uid degrades to the older name-based
    /// behaviour rather than dropping the fact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    /// `hook_event_name` as Claude reported it.
    pub event: String,
    /// The untouched hook stdin. Stored verbatim as the event payload.
    pub payload: serde_json::Value,
    /// True when the agent is blocked until we answer.
    #[serde(default)]
    pub wait: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterSession {
    pub session_id: String,
    /// Minted by `cc claude` at spawn. Optional only so a supervisor left over
    /// from an older build can still register; a new one always sends it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    pub tmux_session: String,
    pub tmux_socket: String,
    pub cwd: String,
    pub supervisor_pid: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_bin: Option<String>,
    pub started_at: String,
    /// What this supervisor is able to honour, as [`crate::PROTOCOL_MINOR`].
    ///
    /// Defaults to `0` for a supervisor left over from an in-place upgrade, and
    /// that default is load-bearing rather than cosmetic: a supervisor below
    /// minor 3 silently ignores [`SupervisorRequest::SendText::expect`], so the
    /// daemon cannot bind an approval to the prompt it was created for. Remote
    /// actuation of a permission prompt is refused in that case rather than
    /// performed against an unproven screen.
    #[serde(default)]
    pub protocol_minor: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SupervisorRequest {
    /// Type into the session's TTY, but only once the expected prompt is
    /// confirmed on screen. This is the mirror model's answer path: phone input
    /// becomes literal keyboard input, so first-answer-wins is physical.
    SendText {
        text: String,
        require: PromptPresence,
        /// Send Enter after the text. False lets the phone stage a draft.
        #[serde(default = "default_true")]
        submit: bool,
        /// The prompt this text is an answer to, as it looked when the card was
        /// created. Re-checked by the supervisor in the same breath as the
        /// presence check — the only place where "the prompt is there" and "the
        /// keys are sent" are close enough together for the answer to be about
        /// the prompt a human actually saw.
        ///
        /// `None` for a free-text takeover into the composer, which is not an
        /// answer to any prompt and whose interlock is composer presence.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        expect: Option<PromptFingerprint>,
    },
    /// Text snapshot of the pane. Presence checks and mirroring only —
    /// terminal bytes are never parsed for semantics.
    Capture {
        #[serde(default = "default_capture_lines")]
        lines: u32,
        /// Capture the **visible** pane and no scrollback, whatever `lines`
        /// says. Every presence and identity decision uses this: a prompt that
        /// has scrolled off the screen is history, and history must never
        /// authorise a keystroke.
        #[serde(default)]
        visible_only: bool,
    },
    Ping,
}

fn default_true() -> bool {
    true
}

fn default_capture_lines() -> u32 {
    80
}

/// Proof that the prompt now on screen is the one an approval was created for.
///
/// Not a hash of the whole pane: a pane carries a cursor, a spinner and elapsed
/// counters, so a whole-pane hash would refuse every answer. It covers the
/// prompt *block* — the line the presence needle matched, a bounded run of the
/// lines above it (the command being asked about) and everything below it (the
/// option list and its footer) — which is exactly the region that is static for
/// as long as one prompt is up and different for the next one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PromptFingerprint {
    /// The normalised needle that located the block, carried so the checker
    /// extracts the same region rather than guessing at one.
    pub needle: String,
    /// sha256 of the normalised block.
    pub sha: String,
}

/// Lines above the matched needle folded into a prompt's identity.
///
/// Bounded rather than unbounded: everything above the prompt is streamed agent
/// output, and hashing an arbitrary amount of it would make the fingerprint
/// depend on how much scrolled past rather than on which prompt is showing.
const PROMPT_CONTEXT_LINES: usize = 12;

/// The prompt block a fingerprint covers, normalised, or `None` when the pane
/// does not contain the needle on any single line.
///
/// `None` is a refusal, not an absence: it means the identity of what is on
/// screen could not be established, and the caller must fail toward the human.
pub fn prompt_block(pane_text: &str, needle: &str) -> Option<String> {
    let needle = normalize_for_match(needle);
    if needle.is_empty() {
        return None;
    }
    let lines: Vec<&str> = pane_text.lines().collect();
    // The *last* match, not the first: if one visible pane somehow shows the
    // wording twice, the live prompt is the lower one.
    let anchor = lines
        .iter()
        .rposition(|line| normalize_for_match(line).contains(&needle))?;
    let start = anchor.saturating_sub(PROMPT_CONTEXT_LINES);
    let mut block: Vec<String> = lines[start..]
        .iter()
        .map(|line| normalize_for_match(line))
        .collect();
    // Trailing blank lines are padding, and how many of them there are depends
    // on the pane height rather than on the prompt.
    while block.last().is_some_and(|line| line.is_empty()) {
        block.pop();
    }
    if block.is_empty() {
        return None;
    }
    Some(block.join("\n"))
}

/// Fingerprint the prompt a needle matched, or `None` if it cannot be located.
pub fn prompt_fingerprint(pane_text: &str, needle: &str) -> Option<PromptFingerprint> {
    let block = prompt_block(pane_text, needle)?;
    Some(PromptFingerprint {
        needle: normalize_for_match(needle),
        sha: crate::hash::sha256_hex(block.as_bytes()),
    })
}

impl PromptFingerprint {
    /// Is the prompt this was taken from still the one on screen?
    pub fn still_on_screen(&self, pane_text: &str) -> bool {
        match prompt_block(pane_text, &self.needle) {
            Some(block) => crate::hash::sha256_hex(block.as_bytes()) == self.sha,
            // Cannot locate the block at all: not a match, and never a pass.
            None => false,
        }
    }
}

/// What must be visible in `capture-pane` output before keys are injected.
///
/// Matching is whitespace-insensitive: Claude's renderer pads with box-drawing
/// glyphs and inconsistent spacing, and the raw render stream contains zero
/// 0x20 bytes at all, so any space-sensitive needle is a latent flake.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "mode", rename_all = "snake_case")]
pub enum PromptPresence {
    /// The composer is accepting input.
    InputBox,
    /// A permission prompt is on screen ("Do you want to proceed?").
    PermissionPrompt,
    /// Caller-supplied needles; any one matching is enough.
    AnyOf { needles: Vec<String> },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum SupervisorResult {
    /// Keys were injected; `matched` is the needle that authorised it.
    Sent {
        matched: String,
    },
    /// Presence check failed. Nothing was typed.
    Refused {
        reason: String,
    },
    Snapshot {
        text: String,
    },
    Pong,
    Error {
        message: String,
    },
}

/// Strip *all* whitespace and lowercase, for prompt-presence matching.
pub fn normalize_for_match(s: &str) -> String {
    s.chars()
        .filter(|c| !c.is_whitespace())
        .flat_map(|c| c.to_lowercase())
        .collect()
}

impl PromptPresence {
    /// Default needles per mode. Kept here (not in the daemon) so the shim and
    /// the daemon can never drift, and overridable from config because Claude's
    /// TUI copy is the single most churn-prone surface we depend on.
    pub fn default_needles(&self) -> Vec<String> {
        match self {
            PromptPresence::InputBox => {
                vec!["forshortcuts".to_string(), "foragents".to_string()]
            }
            PromptPresence::PermissionPrompt => {
                vec!["doyouwanttoproceed".to_string(), "esctocancel".to_string()]
            }
            PromptPresence::AnyOf { needles } => {
                needles.iter().map(|n| normalize_for_match(n)).collect()
            }
        }
    }

    /// Returns the needle that matched, if any.
    pub fn find_match(&self, pane_text: &str, overrides: Option<&[String]>) -> Option<String> {
        let haystack = normalize_for_match(pane_text);
        let owned;
        let needles: &[String] = match overrides {
            Some(list) if !list.is_empty() => {
                owned = list
                    .iter()
                    .map(|n| normalize_for_match(n))
                    .collect::<Vec<_>>();
                &owned
            }
            _ => {
                owned = self.default_needles();
                &owned
            }
        };
        needles
            .iter()
            .find(|needle| !needle.is_empty() && haystack.contains(needle.as_str()))
            .cloned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verbatim from `tmux -L codeconnect capture-pane -p -J` against a live
    /// permission prompt on claude 2.1.220.
    const PERMISSION_PANE: &str = "\
 Bash command
   touch /private/tmp/ccprobe_c.txt
   Create empty file

 Do you want to proceed?
 ❯ 1. Yes
   2. Yes, and always allow access to tmp/ from this project
   3. No
 Esc to cancel · Tab to amend · ctrl+e to explain";

    const IDLE_PANE: &str = "\
❯
────────────────────────────────────────
  ⏸ manual mode on · ? for shortcuts · ← for agents                    ● high · /effort";

    #[test]
    fn permission_prompt_detected_on_real_pane() {
        let m = PromptPresence::PermissionPrompt
            .find_match(PERMISSION_PANE, None)
            .expect("must detect the live permission prompt");
        assert_eq!(m, "doyouwanttoproceed");
    }

    #[test]
    fn permission_prompt_not_detected_on_idle_pane() {
        assert!(PromptPresence::PermissionPrompt
            .find_match(IDLE_PANE, None)
            .is_none());
    }

    #[test]
    fn input_box_detected_on_idle_pane() {
        assert!(PromptPresence::InputBox
            .find_match(IDLE_PANE, None)
            .is_some());
    }

    #[test]
    fn matching_survives_reflow_and_padding() {
        // Same words, different wrapping and spacing: must still match.
        let reflowed = "Do  you\n want to\tproceed?";
        assert!(PromptPresence::PermissionPrompt
            .find_match(reflowed, None)
            .is_some());
    }

    #[test]
    fn overrides_replace_defaults() {
        let m = PromptPresence::PermissionPrompt
            .find_match(PERMISSION_PANE, Some(&["Create empty file".to_string()]))
            .unwrap();
        assert_eq!(m, "createemptyfile");
        assert!(PromptPresence::PermissionPrompt
            .find_match(PERMISSION_PANE, Some(&["nothing here".to_string()]))
            .is_none());
    }

    #[test]
    fn a_dismissed_prompt_is_told_apart_from_a_pane_we_cannot_read() {
        // The local-resolution rule is "prompt gone AND composer back". These
        // are the three panes it has to tell apart, and the middle one is the
        // false positive that a bare absence check would trip on.
        let answered = |pane: &str| {
            PromptPresence::PermissionPrompt
                .find_match(pane, None)
                .is_none()
                && PromptPresence::InputBox.find_match(pane, None).is_some()
        };
        assert!(!answered(PERMISSION_PANE), "the prompt is still up");
        assert!(
            !answered("some other tmux window entirely\n$ ls"),
            "a switched-away pane has no prompt either, and must not read as answered"
        );
        assert!(!answered(""), "an empty capture proves nothing");
        assert!(answered(IDLE_PANE), "prompt gone and the composer is back");
    }

    #[test]
    fn empty_needles_never_match_everything() {
        assert!(PromptPresence::AnyOf {
            needles: vec![String::new()]
        }
        .find_match(PERMISSION_PANE, None)
        .is_none());
    }

    #[test]
    fn frames_round_trip() {
        let frame = ClientFrame::Hook(HookPost {
            session_id: "cc-1".into(),
            session_uid: Some("01K1B3XQ8ZC0DE5FGH7JKMNPQR".into()),
            event: "PermissionRequest".into(),
            payload: serde_json::json!({"tool_name": "Bash"}),
            wait: true,
        });
        let line = serde_json::to_string(&frame).unwrap();
        assert!(line.contains("\"type\":\"hook\""));
        let back: ClientFrame = serde_json::from_str(&line).unwrap();
        match back {
            ClientFrame::Hook(post) => {
                assert_eq!(post.session_id, "cc-1");
                assert_eq!(
                    post.session_uid.as_deref(),
                    Some("01K1B3XQ8ZC0DE5FGH7JKMNPQR")
                );
                assert!(post.wait);
            }
            other => panic!("wrong frame: {other:?}"),
        }
    }

    #[test]
    fn a_hook_or_registration_from_an_older_build_still_decodes() {
        // The in-place upgrade case, which is not hypothetical: a session
        // running when the daemon is upgraded keeps posting from the settings
        // file it was started with, and its supervisor is the old binary.
        let post: ClientFrame = serde_json::from_str(
            r#"{"type":"hook","session_id":"cc-1","event":"PreToolUse","payload":{}}"#,
        )
        .unwrap();
        match post {
            ClientFrame::Hook(post) => assert_eq!(post.session_uid, None),
            other => panic!("wrong frame: {other:?}"),
        }

        let register: ClientFrame = serde_json::from_str(
            r#"{"type":"register","session_id":"cc-1","tmux_session":"cc-1",
                "tmux_socket":"codeconnect","cwd":"/tmp","supervisor_pid":42,
                "started_at":"t"}"#,
        )
        .unwrap();
        match register {
            ClientFrame::Register(info) => {
                assert_eq!(info.session_uid, None);
                assert_eq!(
                    info.protocol_minor, 0,
                    "a supervisor that does not say what it can honour must be \
                     assumed to honour nothing added since"
                );
            }
            other => panic!("wrong frame: {other:?}"),
        }
    }

    // -------------------------------------------------------- prompt identity

    /// The same permission prompt, one command later. Verbatim shape from
    /// claude 2.1.220; only the command and the path differ.
    const SECOND_PERMISSION_PANE: &str = "\
 Bash command
   touch /private/tmp/ccprobe_d.txt
   Create empty file

 Do you want to proceed?
 ❯ 1. Yes
   2. Yes, and always allow access to tmp/ from this project
   3. No
 Esc to cancel · Tab to amend · ctrl+e to explain";

    #[test]
    fn a_fingerprint_matches_its_own_prompt_and_no_other() {
        let taken = prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed")
            .expect("the live prompt must be fingerprintable");
        assert!(taken.still_on_screen(PERMISSION_PANE));
        // The failure this guards against: a *different* prompt, same wording,
        // same options. Answering it with the previous card would type into it.
        assert!(
            !taken.still_on_screen(SECOND_PERMISSION_PANE),
            "two different prompts must not share an identity"
        );
        // And a pane with no prompt at all proves nothing, so it never passes.
        assert!(!taken.still_on_screen(IDLE_PANE));
        assert!(!taken.still_on_screen(""));
    }

    #[test]
    fn a_fingerprint_survives_the_reflow_a_real_pane_does() {
        // The pane is re-rendered constantly; what must not change is the
        // prompt block itself. Padding and case are normalised away.
        let taken = prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed").unwrap();
        let repadded = PERMISSION_PANE.replace("   ", "     ").replace('?', "?  ");
        assert!(
            taken.still_on_screen(&repadded),
            "whitespace churn must not read as a different prompt"
        );
    }

    #[test]
    fn a_moved_selection_is_not_the_same_prompt() {
        // The operator arrowed down to "No" while the phone was deciding.
        // Refusing is correct: whoever is at the keyboard owns this prompt.
        let taken = prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed").unwrap();
        let moved = PERMISSION_PANE
            .replace(" ❯ 1. Yes", "   1. Yes")
            .replace("   3. No", " ❯ 3. No");
        assert!(!taken.still_on_screen(&moved));
    }

    #[test]
    fn a_prompt_that_cannot_be_located_yields_no_fingerprint() {
        assert!(prompt_fingerprint(IDLE_PANE, "doyouwanttoproceed").is_none());
        assert!(prompt_fingerprint(PERMISSION_PANE, "").is_none());
        assert!(prompt_fingerprint("", "doyouwanttoproceed").is_none());
    }

    #[test]
    fn a_fingerprint_round_trips_over_the_socket() {
        let request = SupervisorRequest::SendText {
            text: "1".into(),
            require: PromptPresence::PermissionPrompt,
            submit: true,
            expect: prompt_fingerprint(PERMISSION_PANE, "doyouwanttoproceed"),
        };
        let line = serde_json::to_string(&request).unwrap();
        assert!(line.contains("\"expect\""), "{line}");
        match serde_json::from_str::<SupervisorRequest>(&line).unwrap() {
            SupervisorRequest::SendText { expect, .. } => {
                assert!(expect.unwrap().still_on_screen(PERMISSION_PANE));
            }
            other => panic!("wrong request: {other:?}"),
        }
    }

    #[test]
    fn a_capture_asks_for_the_visible_pane_only_when_it_says_so() {
        // The default stays "with scrollback" so a mirroring snapshot keeps its
        // context; every presence decision opts in explicitly.
        let legacy: SupervisorRequest =
            serde_json::from_str(r#"{"kind":"capture","lines":80}"#).unwrap();
        match legacy {
            SupervisorRequest::Capture { visible_only, .. } => assert!(!visible_only),
            other => panic!("wrong request: {other:?}"),
        }
        let scoped: SupervisorRequest =
            serde_json::from_str(r#"{"kind":"capture","lines":80,"visible_only":true}"#).unwrap();
        match scoped {
            SupervisorRequest::Capture { visible_only, .. } => assert!(visible_only),
            other => panic!("wrong request: {other:?}"),
        }
    }

    #[test]
    fn daemon_info_tells_launchd_apart_from_a_hand_started_process() {
        let mut info = DaemonInfo {
            pid: 4242,
            version: "0.1.0".into(),
            protocol_version: crate::PROTOCOL_VERSION,
            protocol_minor: crate::PROTOCOL_MINOR,
            started_at: "2026-07-31T10:00:00.000Z".into(),
            launchd_label: Some(crate::LAUNCHD_LABEL.to_string()),
            endpoint_host: "host.ts.net".into(),
            endpoint_port: 8787,
            tls: true,
            sessions: 2,
        };
        assert!(info.is_launchd_managed());

        // A foreground `ccd &` and a job with somebody else's label are both
        // "not ours to restart", and must not be confused with each other.
        info.launchd_label = None;
        assert!(!info.is_launchd_managed());
        info.launchd_label = Some("com.example.other".into());
        assert!(!info.is_launchd_managed());

        let line = serde_json::to_string(&DaemonFrame::Daemon(info)).unwrap();
        assert!(line.contains("\"type\":\"daemon\""), "{line}");
        let _: DaemonFrame = serde_json::from_str(&line).unwrap();
    }

    #[test]
    fn pairing_frames_round_trip() {
        let request = ClientFrame::CreatePairing {
            ttl_secs: crate::pairing::PAIRING_TTL_SECS,
            allow_ssh: true,
        };
        let line = serde_json::to_string(&request).unwrap();
        assert!(line.contains("\"type\":\"create_pairing\""), "{line}");
        match serde_json::from_str::<ClientFrame>(&line).unwrap() {
            ClientFrame::CreatePairing {
                allow_ssh,
                ttl_secs,
            } => {
                assert!(allow_ssh);
                assert_eq!(ttl_secs, 300);
            }
            other => panic!("wrong frame: {other:?}"),
        }

        let reply = DaemonFrame::Pairing {
            code: "ABCD2345".into(),
            expires_at: "2026-07-31T10:05:00.000Z".into(),
            host: "host.ts.net".into(),
            port: 8787,
            tls: true,
            allow_ssh: true,
        };
        let line = serde_json::to_string(&reply).unwrap();
        assert!(line.contains("\"type\":\"pairing\""), "{line}");
        let _: DaemonFrame = serde_json::from_str(&line).unwrap();
    }

    #[test]
    fn ssh_consent_defaults_to_off_when_the_flag_is_absent() {
        // A `cc` too old to know about `--ssh` must never be read as consenting.
        let frame: ClientFrame =
            serde_json::from_str(r#"{"type":"create_pairing","ttl_secs":300}"#).unwrap();
        match frame {
            ClientFrame::CreatePairing { allow_ssh, .. } => assert!(!allow_ssh),
            other => panic!("wrong frame: {other:?}"),
        }
    }

    #[test]
    fn revoke_defaults_to_the_whole_device_not_just_ssh() {
        let frame: ClientFrame =
            serde_json::from_str(r#"{"type":"revoke_device","device":"iPhone"}"#).unwrap();
        match frame {
            ClientFrame::RevokeDevice { device, ssh_only } => {
                assert_eq!(device, "iPhone");
                assert!(!ssh_only, "a bare revoke must revoke everything");
            }
            other => panic!("wrong frame: {other:?}"),
        }
    }

    #[test]
    fn send_text_defaults_to_submitting() {
        let req: SupervisorRequest = serde_json::from_str(
            r#"{"kind":"send_text","text":"hi","require":{"mode":"input_box"}}"#,
        )
        .unwrap();
        match req {
            SupervisorRequest::SendText { submit, .. } => assert!(submit),
            other => panic!("wrong request: {other:?}"),
        }
    }
}
