//! `cc-hook` — invoked by Claude Code on every wired hook event.
//!
//! Two hard rules, because this process sits in the agent's critical path:
//!
//! 1. **Always exit 0.** A non-zero exit from a PreToolUse hook is a *blocking
//!    error* in Claude Code. A crash in CodeConnect must never look like a
//!    denial, so every failure path here degrades to "print nothing, exit 0" —
//!    which is behaviourally identical to the hook not being installed at all.
//! 2. **Never block longer than promised.** Reaching the daemon is bounded by
//!    `--connect-timeout-ms` (default 200ms) and waiting for a decision by
//!    `--gate-timeout-ms`. Observability events do not wait at all.
//!
//! Diagnostics go to a log file, never to stderr: hook stderr is surfaced in the
//! transcript and would pollute the session the user is trying to work in.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::Shutdown;
use std::os::unix::net::UnixStream;
use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::thread;
use std::time::Duration;

use protocol::hook::{HookDecision, HookEventName, HookInput};
use protocol::ipc::{ClientFrame, DaemonFrame, HookPost, MAX_FRAME_BYTES};

const UNREACHABLE_REASON: &str = "CodeConnect: daemon unreachable, deferring to local operator";
const TIMEOUT_REASON: &str =
    "CodeConnect: held for you but no answer arrived, deferring to local operator";

struct Args {
    session: Option<String>,
    session_uid: Option<String>,
    event: Option<String>,
    gate: bool,
    gate_timeout: Duration,
    connect_timeout: Duration,
    unreachable_ask: bool,
    socket: PathBuf,
}

impl Default for Args {
    fn default() -> Self {
        Args {
            session: None,
            session_uid: None,
            event: None,
            gate: false,
            gate_timeout: Duration::from_secs(120),
            connect_timeout: Duration::from_millis(200),
            unreachable_ask: false,
            socket: protocol::socket_path(),
        }
    }
}

fn parse_args<I: Iterator<Item = String>>(mut it: I) -> Args {
    let mut args = Args::default();
    while let Some(arg) = it.next() {
        match arg.as_str() {
            "--session" => args.session = it.next(),
            "--session-uid" => args.session_uid = it.next(),
            "--event" => args.event = it.next(),
            "--gate" => args.gate = true,
            "--unreachable-ask" => args.unreachable_ask = true,
            "--gate-timeout-ms" => {
                if let Some(ms) = it.next().and_then(|v| v.parse::<u64>().ok()) {
                    args.gate_timeout = Duration::from_millis(ms);
                }
            }
            "--connect-timeout-ms" => {
                if let Some(ms) = it.next().and_then(|v| v.parse::<u64>().ok()) {
                    args.connect_timeout = Duration::from_millis(ms);
                }
            }
            "--socket" => {
                if let Some(path) = it.next() {
                    args.socket = PathBuf::from(path);
                }
            }
            // Unknown flags are ignored rather than fatal: a settings file
            // generated by a newer `codeconnect` must not break an older `cc-hook`.
            _ => {}
        }
    }
    args
}

fn main() {
    // Deliberately infallible: `run` swallows everything.
    run();
    std::process::exit(0);
}

fn run() {
    // Answered before touching stdin: a hook binary blocks until EOF, so
    // `cc-hook --version` from an install script or a terminal would otherwise
    // hang forever waiting for input that is never coming.
    if std::env::args().any(|arg| arg == "--version") {
        println!("cc-hook {}", env!("CARGO_PKG_VERSION"));
        return;
    }

    let args = parse_args(std::env::args().skip(1));

    let mut stdin_bytes = Vec::new();
    if std::io::stdin()
        .take(MAX_FRAME_BYTES as u64)
        .read_to_end(&mut stdin_bytes)
        .is_err()
    {
        debug_log("failed to read stdin");
        return;
    }

    let payload: serde_json::Value = match serde_json::from_slice(&stdin_bytes) {
        Ok(value) => value,
        Err(err) => {
            // Still report it: a payload we cannot parse is exactly the signal
            // that Claude Code's hook schema drifted, and silence would hide it.
            serde_json::json!({
                "_codeconnect_parse_error": err.to_string(),
                "_raw": String::from_utf8_lossy(&stdin_bytes),
            })
        }
    };

    let input: HookInput = serde_json::from_value(payload.clone()).unwrap_or_default();
    let event_name = resolve_event(&args, &input);
    let session_id = resolve_session(&args, &input);

    let post = HookPost {
        session_id,
        session_uid: resolve_session_uid(&args),
        event: event_name.as_str().to_string(),
        payload,
        wait: args.gate,
    };

    let decision = match post_to_daemon(&args, &post) {
        Ok(decision) => decision,
        Err(reason) => {
            debug_log(&format!("daemon path failed: {reason}"));
            fallback_decision(&args, &event_name, &reason)
        }
    };

    if let Some(output) = decision.render(&event_name) {
        // A failed write to stdout is not worth blocking a tool call over.
        let mut out = std::io::stdout();
        let _ = out.write_all(output.as_bytes());
        let _ = out.write_all(b"\n");
        let _ = out.flush();
    }
}

fn resolve_event(args: &Args, input: &HookInput) -> HookEventName {
    // Claude's own field wins; the CLI flag is the fallback so we still route
    // correctly when a payload arrives malformed.
    match input.hook_event_name.as_deref() {
        Some(name) if !name.is_empty() => HookEventName::parse(name),
        _ => HookEventName::parse(args.event.as_deref().unwrap_or("Unknown")),
    }
}

fn resolve_session(args: &Args, input: &HookInput) -> String {
    if let Some(session) = args.session.as_deref().filter(|s| !s.is_empty()) {
        return session.to_string();
    }
    if let Ok(session) = std::env::var(protocol::ENV_SESSION) {
        if !session.is_empty() {
            return session;
        }
    }
    // Last resort: key by Claude's own session uuid so events are still
    // captured for a session that CodeConnect did not launch. The daemon
    // registers it as an adopted session rather than dropping the fact.
    match input.session_id.as_deref() {
        Some(uuid) if !uuid.is_empty() => format!("claude:{uuid}"),
        _ => "unknown".to_string(),
    }
}

/// The run this hook belongs to, if we were told.
///
/// Validated here rather than trusted: the value reaches the daemon as an event
/// log key, and a malformed one would create a second identity for a session
/// that already has one. A `None` is safe — the daemon resolves the name — so
/// dropping a bad value is strictly better than forwarding it.
fn resolve_session_uid(args: &Args) -> Option<String> {
    args.session_uid
        .clone()
        .or_else(|| std::env::var(protocol::ENV_SESSION_UID).ok())
        .filter(|uid| {
            if protocol::uid::is_well_formed(uid) {
                true
            } else {
                debug_log(&format!("ignoring malformed session uid {uid:?}"));
                false
            }
        })
}

/// What to do when the daemon does not answer.
///
/// The default is silence — behaviourally identical to plain `claude`, which is
/// the whole promise of the shim. `--unreachable-ask` opts into the louder
/// behaviour on PreToolUse, where (and only where) Claude renders our reason
/// string to the local operator.
fn fallback_decision(args: &Args, event: &HookEventName, reason: &str) -> HookDecision {
    if !args.gate {
        return HookDecision::passthrough();
    }
    let text = if reason == "timeout" {
        TIMEOUT_REASON
    } else {
        UNREACHABLE_REASON
    };
    match event {
        // Renders nothing on claude 2.1.220, but it is the semantically correct
        // answer and costs nothing if a future build starts honouring it.
        HookEventName::PermissionRequest => HookDecision::ask(text),
        HookEventName::PreToolUse if args.unreachable_ask => HookDecision::ask(text),
        _ => HookDecision::passthrough(),
    }
}

/// Post the frame and, for gate events, wait for the daemon's decision.
/// `Err(reason)` means "no decision from the daemon" — never a hard failure.
fn post_to_daemon(args: &Args, post: &HookPost) -> Result<HookDecision, String> {
    let mut stream = connect_with_timeout(&args.socket, args.connect_timeout)
        .ok_or_else(|| "connect".to_string())?;

    let write_timeout = if args.gate {
        args.gate_timeout.min(Duration::from_secs(5))
    } else {
        Duration::from_secs(1)
    };
    let _ = stream.set_write_timeout(Some(write_timeout));

    let line = serde_json::to_string(&ClientFrame::Hook(post.clone()))
        .map_err(|err| format!("encode: {err}"))?;
    stream
        .write_all(line.as_bytes())
        .and_then(|()| stream.write_all(b"\n"))
        .and_then(|()| stream.flush())
        .map_err(|err| format!("write: {err}"))?;
    // Half-close so the daemon sees a clean end-of-request even if it reads to EOF.
    let _ = stream.shutdown(Shutdown::Write);

    if !args.gate {
        return Ok(HookDecision::passthrough());
    }

    let _ = stream.set_read_timeout(Some(args.gate_timeout));
    let mut reader = BufReader::new(stream);
    let mut response = String::new();
    match reader.read_line(&mut response) {
        Ok(0) => Err("eof".to_string()),
        Ok(_) => match serde_json::from_str::<DaemonFrame>(response.trim()) {
            Ok(DaemonFrame::HookReply { decision }) => Ok(decision),
            Ok(DaemonFrame::Error { message }) => Err(format!("daemon error: {message}")),
            Ok(other) => Err(format!("unexpected frame: {other:?}")),
            Err(err) => Err(format!("decode: {err}")),
        },
        Err(err)
            if err.kind() == std::io::ErrorKind::WouldBlock
                || err.kind() == std::io::ErrorKind::TimedOut =>
        {
            Err("timeout".to_string())
        }
        Err(err) => Err(format!("read: {err}")),
    }
}

/// `UnixStream::connect` has no timeout in std. A connect to an AF_UNIX path is
/// normally instantaneous, but it *can* block when the listener's backlog is
/// full — precisely the situation where a wedged daemon must not wedge the
/// agent. The worker thread is abandoned on timeout rather than joined; the
/// process is about to exit, so the OS reclaims it.
fn connect_with_timeout(path: &Path, timeout: Duration) -> Option<UnixStream> {
    let (tx, rx) = mpsc::channel();
    let path = path.to_path_buf();
    thread::Builder::new()
        .name("cc-hook-connect".to_string())
        .spawn(move || {
            let _ = tx.send(UnixStream::connect(&path));
        })
        .ok()?;
    match rx.recv_timeout(timeout) {
        Ok(Ok(stream)) => Some(stream),
        _ => None,
    }
}

fn debug_log(message: &str) {
    if std::env::var_os("CODECONNECT_DEBUG").is_none() {
        return;
    }
    let dir = protocol::logs_dir();
    if std::fs::create_dir_all(&dir).is_err() {
        return;
    }
    if let Ok(mut file) = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(dir.join("cc-hook.log"))
    {
        let _ = writeln!(file, "{} {}", protocol::time::now_rfc3339(), message);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use protocol::hook::Decision;

    fn args_from(list: &[&str]) -> Args {
        parse_args(list.iter().map(|s| s.to_string()))
    }

    #[test]
    fn parses_flags_and_ignores_unknown_ones() {
        let args = args_from(&[
            "--session",
            "cc-3",
            "--session-uid",
            "01K1B3XQ8ZC0DE5FGH7JKMNPQR",
            "--event",
            "PermissionRequest",
            "--gate",
            "--gate-timeout-ms",
            "5000",
            "--future-flag",
            "value",
        ]);
        assert_eq!(args.session.as_deref(), Some("cc-3"));
        assert_eq!(
            args.session_uid.as_deref(),
            Some("01K1B3XQ8ZC0DE5FGH7JKMNPQR")
        );
        assert_eq!(args.event.as_deref(), Some("PermissionRequest"));
        assert!(args.gate);
        assert_eq!(args.gate_timeout, Duration::from_millis(5000));
        assert!(!args.unreachable_ask);
    }

    #[test]
    fn a_session_uid_is_forwarded_only_when_it_is_one() {
        std::env::remove_var(protocol::ENV_SESSION_UID);
        assert_eq!(
            resolve_session_uid(&args_from(&["--session-uid", "01K1B3XQ8ZC0DE5FGH7JKMNPQR"])),
            Some("01K1B3XQ8ZC0DE5FGH7JKMNPQR".to_string())
        );
        // A truncated or hand-edited value must not become a second identity
        // for a session that already has one; the daemon's name resolution is
        // the correct fallback.
        assert_eq!(
            resolve_session_uid(&args_from(&["--session-uid", "cc-1"])),
            None
        );
        assert_eq!(
            resolve_session_uid(&args_from(&["--session-uid", ""])),
            None
        );
        assert_eq!(resolve_session_uid(&args_from(&[])), None);
    }

    #[test]
    fn a_settings_file_from_an_older_cc_still_posts() {
        // The in-place upgrade case: a session started before `--session-uid`
        // existed keeps invoking the hook without it, and must keep working.
        let args = args_from(&["--session", "cc-1", "--event", "PreToolUse"]);
        assert_eq!(args.session_uid, None);
        assert_eq!(args.session.as_deref(), Some("cc-1"));
    }

    #[test]
    fn malformed_numeric_flag_keeps_the_default() {
        let args = args_from(&["--gate-timeout-ms", "not-a-number"]);
        assert_eq!(args.gate_timeout, Duration::from_secs(120));
    }

    #[test]
    fn payload_event_name_wins_over_flag() {
        let args = args_from(&["--event", "PreToolUse"]);
        let input: HookInput =
            serde_json::from_str(r#"{"hook_event_name":"PermissionRequest"}"#).unwrap();
        assert_eq!(
            resolve_event(&args, &input),
            HookEventName::PermissionRequest
        );
    }

    #[test]
    fn falls_back_to_flag_when_payload_is_unusable() {
        let args = args_from(&["--event", "PostToolUse"]);
        let input = HookInput::default();
        assert_eq!(resolve_event(&args, &input), HookEventName::PostToolUse);
    }

    #[test]
    fn session_falls_back_to_claude_uuid() {
        let args = args_from(&[]);
        std::env::remove_var(protocol::ENV_SESSION);
        let input: HookInput =
            serde_json::from_str(r#"{"session_id":"8f37b678-558a-4aae-a0b9-eaa9e9bf3103"}"#)
                .unwrap();
        assert_eq!(
            resolve_session(&args, &input),
            "claude:8f37b678-558a-4aae-a0b9-eaa9e9bf3103"
        );
    }

    #[test]
    fn non_gate_events_never_alter_behaviour_when_daemon_is_down() {
        let args = args_from(&["--event", "PostToolUse"]);
        let decision = fallback_decision(&args, &HookEventName::PostToolUse, "connect");
        assert_eq!(decision.decision, Decision::Passthrough);
        assert_eq!(decision.render(&HookEventName::PostToolUse), None);
    }

    #[test]
    fn gate_unreachable_defaults_to_silent_passthrough_on_pretooluse() {
        // Silence is the honest default: forcing a prompt on every tool call
        // because *our* daemon died would break "behaves like plain claude".
        let args = args_from(&["--gate"]);
        let decision = fallback_decision(&args, &HookEventName::PreToolUse, "connect");
        assert_eq!(decision.decision, Decision::Passthrough);
    }

    #[test]
    fn unreachable_ask_renders_the_reason_on_pretooluse() {
        let args = args_from(&["--gate", "--unreachable-ask"]);
        let decision = fallback_decision(&args, &HookEventName::PreToolUse, "connect");
        let out = decision.render(&HookEventName::PreToolUse).unwrap();
        assert!(out.contains(UNREACHABLE_REASON), "{out}");
        assert!(out.contains("\"permissionDecision\":\"ask\""), "{out}");
    }

    #[test]
    fn timeout_reason_is_distinct_and_honest() {
        let args = args_from(&["--gate", "--unreachable-ask"]);
        let decision = fallback_decision(&args, &HookEventName::PreToolUse, "timeout");
        let out = decision.render(&HookEventName::PreToolUse).unwrap();
        assert!(out.contains("held for you"), "{out}");
    }

    #[test]
    fn permission_request_gate_stays_silent_but_semantically_ask() {
        let args = args_from(&["--gate"]);
        let decision = fallback_decision(&args, &HookEventName::PermissionRequest, "connect");
        assert_eq!(decision.decision, Decision::Ask);
        assert_eq!(decision.render(&HookEventName::PermissionRequest), None);
    }

    #[test]
    fn version_flag_is_recognised_before_stdin_is_touched() {
        // Guards the ordering, which is the whole point: parse_args ignores
        // unknown flags, so nothing else would catch a regression here.
        let source = include_str!("main.rs");
        let version_at = source.find(r#"arg == "--version""#).expect("version check");
        let stdin_at = source.find("std::io::stdin()").expect("stdin read");
        assert!(version_at < stdin_at, "--version must be handled first");
    }

    #[test]
    fn connect_to_missing_socket_gives_up_fast() {
        let start = std::time::Instant::now();
        let result = connect_with_timeout(
            Path::new("/tmp/codeconnect-does-not-exist.sock"),
            Duration::from_millis(200),
        );
        assert!(result.is_none());
        assert!(
            start.elapsed() < Duration::from_millis(500),
            "took {:?}",
            start.elapsed()
        );
    }
}
