import XCTest

@testable import CodeConnect

/// The transcript's local-command grammar, tested against the verbatim
/// content strings a live Claude Code 2.1.221 wrote while `/model sonnet`,
/// `/model fable`, and `/exit` ran — not against hand-idealised fixtures.
final class LocalCommandTests: XCTestCase {

    private let measuredCaveat =
        "<local-command-caveat>Caveat: The messages below were generated by the user while "
        + "running local commands. DO NOT respond to these messages or otherwise consider them "
        + "in your response unless the user explicitly asks you to.</local-command-caveat>"
    private let measuredInvocation =
        "<command-name>/model</command-name>\n            "
        + "<command-message>model</command-message>\n            "
        + "<command-args>sonnet</command-args>"
    private let measuredOutput =
        "<local-command-stdout>Set model to \u{1B}[1mSonnet 5\u{1B}[22m and saved as your "
        + "default for new sessions</local-command-stdout>"

    func testTheThreeMeasuredShapesParse() {
        XCTAssertEqual(LocalCommandLine.parse(measuredCaveat), .caveat)
        XCTAssertEqual(
            LocalCommandLine.parse(measuredInvocation),
            .invocation(command: "/model", args: "sonnet"))
        XCTAssertEqual(
            LocalCommandLine.parse(measuredOutput),
            .output("Set model to Sonnet 5 and saved as your default for new sessions"),
            "the ANSI bold wrapping is styling, not content")
    }

    func testANoArgumentInvocationHasNoTrailingSpace() {
        let exit = LocalCommandLine.parse(
            "<command-name>/exit</command-name>\n            "
                + "<command-message>exit</command-message>\n            "
                + "<command-args></command-args>")
        XCTAssertEqual(exit, .invocation(command: "/exit", args: ""))
        XCTAssertEqual(exit?.invocationText, "/exit")
        XCTAssertEqual(
            LocalCommandLine.parse(measuredInvocation)?.invocationText, "/model sonnet")
    }

    /// Recognition is by leading tag: prose that *mentions* the markup is a
    /// person's words and must never be rewritten.
    func testProseMentioningTheTagsStaysProse() {
        XCTAssertNil(LocalCommandLine.parse("the transcript uses <command-name> tags"))
        XCTAssertNil(LocalCommandLine.parse("ordinary message"))
    }

    func testAnUnclosedTagYieldsTheRestRatherThanNothing() {
        XCTAssertEqual(
            LocalCommandLine.parse("<local-command-stdout>Goodbye!"),
            .output("Goodbye!"))
    }

    func testANSIStrippingIsExactlyCSI() {
        XCTAssertEqual(
            LocalCommandLine.stripANSI("a \u{1B}[1mbold\u{1B}[22m b"), "a bold b")
        XCTAssertEqual(
            LocalCommandLine.stripANSI("plain"), "plain",
            "text without escapes passes through byte-identical")
    }

    /// ECMA-48's final byte is a range (0x40-0x7E), not "a letter": a
    /// sequence ending `~` must not eat the first real character after it.
    func testACSISequenceEndingInTildeConsumesNoContent() {
        XCTAssertEqual(LocalCommandLine.stripANSI("\u{1B}[2~delete"), "delete")
        XCTAssertEqual(
            LocalCommandLine.stripANSI("a\u{1B}[38;5;10mgreen\u{1B}[0mb"), "agreenb",
            "multi-parameter sequences strip whole")
    }

    /// A malformed body — a control byte where only parameters and
    /// intermediates may stand — ends the strip in place. Styling may be
    /// lost; content never is.
    func testAMalformedCSIBodyStopsTheStripInsteadOfEatingContent() {
        XCTAssertEqual(
            LocalCommandLine.stripANSI("\u{1B}[1\ntext"), "\ntext",
            "the newline is content the sequence never legally contained")
        XCTAssertEqual(LocalCommandLine.stripANSI("\u{1B}["), "")
    }

    // MARK: The timeline's use of the grammar

    private func userEvent(seq: UInt64, content: String) throws -> Event {
        let escaped = try String(
            data: JSONEncoder().encode(content), encoding: .utf8)!
        let json = """
            {"seq":\(seq),"session_id":"cc-1","ts":"2026-08-04T20:00:00.000Z",
             "kind":"user_message","source":"transcript",
             "payload":{"type":"user","message":{"role":"user","content":\(escaped)}}}
            """
        return try JSONDecoder().decode(Event.self, from: Data(json.utf8))
    }

    func testTheTimelineRendersCommandsAsCommandsAndOutputAsNotice() throws {
        let events = [
            try userEvent(seq: 1, content: measuredCaveat),
            try userEvent(seq: 2, content: measuredInvocation),
            try userEvent(seq: 3, content: measuredOutput),
            try userEvent(seq: 4, content: "and a real message"),
        ]
        let items = TimelineBuilder.build(events)
        XCTAssertEqual(items.count, 3, "the caveat is boilerplate, not a row: \(items)")

        guard case .userMessage(let command) = items[0].content else {
            return XCTFail("\(items[0])")
        }
        XCTAssertEqual(command, "/model sonnet", "the command, never the markup")

        guard case .notice(let notice) = items[1].content else { return XCTFail("\(items[1])") }
        XCTAssertEqual(
            notice.title,
            "Set model to Sonnet 5 and saved as your default for new sessions")
        XCTAssertFalse(notice.title.contains("\u{1B}"), "no escape byte reaches a row")

        guard case .userMessage(let prose) = items[2].content else {
            return XCTFail("\(items[2])")
        }
        XCTAssertEqual(prose, "and a real message")
    }
}
