//! The vendored guarded-surface references: how they are produced, and the proof that
//! they are still what real codex binaries say.
//!
//! `schema-0.147/guarded-wire-{stable,experimental}.json` and `guarded-argv.json` are the
//! gate's **baseline**; `schema-0.153/…` are the **grounded ceiling** every entry in
//! `codex_broker::guarded_surface::ADJUDICATED_WIRE` points into. Unlike `methods-*.json`
//! (a census of method NAMES), these carry the resolved parameter shapes of the guarded
//! methods, the JSON-RPC envelopes, and the root CLI surface — the things
//! `codeconnect::codex`'s launch gate actually compares an installed binary against.
//!
//! **They are generated by the gate's own projection, never by hand and never by a
//! second implementation.** [`regenerate_the_vendored_references`] writes them using
//! exactly [`codex_broker::guarded_surface`], which is exactly what the launcher runs.
//! A reference produced by a different code path than the gate is a reference that can
//! disagree with the gate about what it means, and the disagreement would surface as a
//! refusal nobody can explain.
//!
//! # Regenerating (the PROVENANCE recipe, executable)
//!
//! ```text
//! for V in 0.147 0.153; do
//!   CODEX=<the $V binary>
//!   OUT=$(mktemp -d)/$V
//!   "$CODEX" app-server generate-json-schema --out "$OUT/stable"
//!   "$CODEX" app-server generate-json-schema --out "$OUT/experimental" --experimental
//!   "$CODEX" completion bash > "$OUT/completion.bash"
//! done
//! CC_REGENERATE_GUARDED_SURFACE_0147=<…/0.147> \
//! CC_REGENERATE_GUARDED_SURFACE_0153=<…/0.153> \
//!   cargo test -p codex-broker --test guarded_surface_reference \
//!   regenerate_the_vendored_references -- --ignored --nocapture
//! ```
//!
//! Regeneration is `#[ignore]`d so it never runs in an ordinary suite: a reference that
//! silently re-derives itself from whatever binary is installed is a gate that always
//! passes. Re-vendoring is a deliberate act with a diff to review.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use codex_broker::guarded_surface::{
    admissible_argv, admissible_wire, baseline_argv, baseline_wire, diff_argv, diff_wire,
    grounded_argv, grounded_wire, guarded_result_types, parse_schema, project_argv, project_bundle,
    ArgvSurface, BundleDocs, GuardedSurface, HIDDEN_ROOT_ALIASES,
};
use serde_json::Value;

fn manifest(sub: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(sub)
}

/// The two bundles the references cover.
///
/// Both, not just `stable`: the app-server is spawned without the experimental
/// capability, so stable is the live wire — but the broker's allowlist and its
/// exhaustiveness proof span both bundles, and a feature toggle can move a method between
/// them. Gating only the bundle we expect to meet would leave the other unmeasured, which
/// is the reading this whole gate exists to stop making.
const BUNDLES: [&str; 2] = ["stable", "experimental"];

/// The two vendored references, by the release each was projected from.
const REFERENCES: [(&str, &str); 2] = [
    ("0.147", "CC_REGENERATE_GUARDED_SURFACE_0147"),
    ("0.153", "CC_REGENERATE_GUARDED_SURFACE_0153"),
];

fn wire_reference_path(release: &str, bundle: &str) -> PathBuf {
    manifest(&format!("schema-{release}/guarded-wire-{bundle}.json"))
}

fn argv_reference_path(release: &str) -> PathBuf {
    manifest(&format!("schema-{release}/guarded-argv.json"))
}

/// Project one generated bundle tree exactly as the launch gate does — both client-side
/// documents, not just the requests.
fn project_bundle_dir(dir: &Path) -> GuardedSurface {
    let read = |path: PathBuf| -> Value {
        let raw = fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        parse_schema(&raw).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
    };
    let client_request = read(dir.join("ClientRequest.json"));
    let client_notification = read(dir.join("ClientNotification.json"));
    let server_request = read(dir.join("ServerRequest.json"));
    let mut results = std::collections::BTreeMap::new();
    for name in guarded_result_types(&client_request).expect("the request document projects") {
        let file = format!("{name}.json");
        let path = ["v2", "v1"]
            .iter()
            .map(|d| dir.join(d).join(&file))
            .find(|p| p.is_file())
            .unwrap_or_else(|| panic!("no {file} under {}", dir.display()));
        results.insert(name, read(path));
    }
    project_bundle(&BundleDocs {
        client_request: &client_request,
        client_notification: &client_notification,
        server_request: &server_request,
        results: &results,
    })
    .expect("the bundle projects")
}

/// Write both vendored references from generated bundle trees. See the module header.
#[test]
#[ignore = "regeneration is a deliberate act; see the module header"]
fn regenerate_the_vendored_references() {
    for (release, env) in REFERENCES {
        let root = PathBuf::from(
            std::env::var(env).unwrap_or_else(|_| panic!("set {env} to the generated tree")),
        );
        for bundle in BUNDLES {
            let surface = project_bundle_dir(&root.join(bundle));
            assert!(
                !surface.is_empty(),
                "{release}/{bundle}: projected an EMPTY guarded surface — refusing to \
                 vendor a reference that would compare equal to anything"
            );
            let text = serde_json::to_string_pretty(&surface).expect("serializes");
            let path = wire_reference_path(release, bundle);
            fs::create_dir_all(path.parent().unwrap()).expect("reference directory");
            fs::write(&path, format!("{text}\n")).expect("write wire reference");
            println!(
                "wrote {} ({} guarded methods)",
                path.display(),
                surface.len()
            );
        }

        let completion = fs::read_to_string(root.join("completion.bash")).expect("completion.bash");
        let argv = project_argv(&completion).expect("the completion script projects");
        let text = serde_json::to_string_pretty(&argv).expect("serializes");
        let path = argv_reference_path(release);
        fs::write(&path, format!("{text}\n")).expect("write argv reference");
        println!(
            "wrote {} ({} subcommands, {} flags)",
            path.display(),
            argv.subcommands.len(),
            argv.flags.len()
        );
    }
}

/// The references are non-vacuous: they name every method the allowlist admits, and no
/// method it refuses.
///
/// This is the check that stops the gate becoming decorative. A reference that lost its
/// methods — a bad regeneration, a truncated write — would compare equal to an equally
/// empty projection and admit every codex ever built. The count is asserted against the
/// allowlist itself rather than a literal, so adding a method to the allowlist without
/// re-vendoring fails HERE, loudly, instead of leaving a hole in the gate.
#[test]
fn the_vendored_references_cover_exactly_the_guarded_methods() {
    let census: BTreeSet<String> = BUNDLES
        .iter()
        .flat_map(|b| {
            let raw =
                fs::read_to_string(manifest(&format!("schema-0.147/methods-{b}.json"))).unwrap();
            let v: Value = serde_json::from_str(&raw).unwrap();
            ["client_requests", "client_notifications"]
                .iter()
                .flat_map(|k| {
                    v[*k]
                        .as_array()
                        .unwrap()
                        .iter()
                        .map(|m| m.as_str().unwrap().to_string())
                        .collect::<Vec<_>>()
                })
                .collect::<Vec<_>>()
        })
        .collect();

    // Every guarded method, in the kind it is guarded as. `initialized` is a
    // NOTIFICATION and is now inside the projection, keyed apart from any request.
    let expected: BTreeSet<String> = census
        .iter()
        .filter(|m| codex_broker::guarded_surface::is_guarded(m))
        .map(|m| {
            if m == "initialized" {
                format!("notification {m}")
            } else {
                format!("request {m}")
            }
        })
        .collect();
    assert!(
        !expected.is_empty(),
        "the allowlist admits nothing — the derivation is broken"
    );

    for (release, load_wire) in [
        ("0.147", baseline_wire as fn(&str) -> GuardedSurface),
        ("0.153", grounded_wire as fn(&str) -> GuardedSurface),
    ] {
        // Per bundle: nothing the allowlist refuses may appear on the CLIENT side. A
        // refused client method in the reference would make the gate refuse a codex over a
        // shape it never forwards.
        //
        // The server side is not filtered that way and must not be: the allowlist keys the
        // client direction only, and the broker relays and classifies EVERY server→client
        // request. Their presence is checked instead — the set is part of the contract,
        // because a new one appearing is exactly the re-grounding signal that says
        // "somebody must decide whether this one is answerable".
        let mut union: BTreeSet<String> = BTreeSet::new();
        for bundle in BUNDLES {
            let have: BTreeSet<String> = load_wire(bundle).keys().cloned().collect();
            let (server, client): (Vec<&String>, Vec<&String>) =
                have.iter().partition(|k| k.starts_with("server-request "));
            let extra: Vec<_> = client
                .into_iter()
                .filter(|k| !expected.contains(*k))
                .collect();
            assert!(
                extra.is_empty(),
                "{release}/{bundle}: the vendored reference names {extra:?}, which the \
                 allowlist refuses on every leg"
            );
            assert!(
                server.len() >= 10,
                "{release}/{bundle}: only {} server→client requests projected; the measured \
                 census is 10 (stable) / 11 (experimental)",
                server.len()
            );
            for answerable in [
                codex_broker::response_capability::COMMAND_EXEC_APPROVAL,
                codex_broker::response_capability::FILE_CHANGE_APPROVAL,
                codex_broker::response_capability::DYNAMIC_TOOL_CALL,
            ] {
                assert!(
                    have.contains(&format!("server-request {answerable}")),
                    "{release}/{bundle}: {answerable} is answerable but its shape is not in \
                     the reference"
                );
            }
            union.extend(
                have.iter()
                    .filter(|k| !k.starts_with("server-request "))
                    .cloned(),
            );
        }

        // Across the two bundles: every guarded method must be described somewhere.
        //
        // Union rather than per-bundle, because the bundles genuinely differ and that
        // asymmetry is itself measured: on 0.147 `thread/turns/list` and
        // `thread/items/list` exist ONLY in the experimental bundle, while the allowlist
        // binds them on both legs. They are guarded methods that the stable wire of
        // 0.147 does not expose at all, and 0.153 promotes them — which the gate reports
        // as an adjudicated `MethodAdded` on the stable bundle.
        let missing: Vec<_> = expected.difference(&union).collect();
        assert!(
            missing.is_empty(),
            "{release}: the vendored reference describes NO bundle for guarded methods \
             {missing:?} — the gate would not compare them at all"
        );
    }
}

/// A vendored reference nobody can reproduce is a number in a file. This re-derives both
/// from real binaries and demands equality — of the PROJECTED VALUE, which is the thing
/// the gate compares. (The serialized bytes are a formatting of that value; asserting
/// them would pin `to_string_pretty`, not the surface.)
///
/// Gated on `CC_CODEX_LIVE=1` plus `CC_CODEX_0147` / `CC_CODEX_0153` naming the binaries,
/// like the other live suites: a machine without those exact releases cannot run it, and
/// a silent skip there is honest where a failure would be noise.
#[test]
fn the_vendored_references_reproduce_from_live_binaries() {
    if std::env::var("CC_CODEX_LIVE").as_deref() != Ok("1") {
        eprintln!("skipped: set CC_CODEX_LIVE=1, CC_CODEX_0147 and CC_CODEX_0153 to run");
        return;
    }

    for (release, env, load_wire, load_argv) in [
        (
            "0.147.",
            "CC_CODEX_0147",
            baseline_wire as fn(&str) -> GuardedSurface,
            baseline_argv as fn() -> ArgvSurface,
        ),
        (
            "0.153.",
            "CC_CODEX_0153",
            grounded_wire as fn(&str) -> GuardedSurface,
            grounded_argv as fn() -> ArgvSurface,
        ),
    ] {
        let Ok(bin) = std::env::var(env) else {
            eprintln!("skipped: {env} is not set");
            continue;
        };

        let tmp = std::env::temp_dir().join(format!(
            "cc-guarded-ref-{}-{}",
            std::process::id(),
            release.trim_end_matches('.')
        ));
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).expect("tempdir");

        let version = std::process::Command::new(&bin)
            .arg("--version")
            .output()
            .expect("codex --version");
        let version = String::from_utf8_lossy(&version.stdout).trim().to_string();
        assert!(
            version.contains(release),
            "{env} must name a {release}x binary; it reported {version:?}"
        );

        for bundle in BUNDLES {
            let out = tmp.join(bundle);
            let mut cmd = std::process::Command::new(&bin);
            cmd.args(["app-server", "generate-json-schema", "--out"])
                .arg(&out);
            if bundle == "experimental" {
                cmd.arg("--experimental");
            }
            let st = cmd.status().expect("generate-json-schema runs");
            assert!(
                st.success(),
                "{release}{bundle}: generate-json-schema failed"
            );

            // Value equality, not a diff summary: the vendored reference must BE the
            // projection, key for key, and a diff that cannot name a difference would
            // otherwise read as agreement.
            let projected = project_bundle_dir(&out);
            assert_eq!(
                load_wire(bundle),
                projected,
                "{release}{bundle}: the vendored reference is not what this binary projects"
            );
        }

        let completion = std::process::Command::new(&bin)
            .args(["completion", "bash"])
            .output()
            .expect("codex completion bash");
        assert!(completion.status.success(), "completion bash failed");
        let projected = project_argv(&String::from_utf8_lossy(&completion.stdout))
            .expect("the live completion script projects");
        assert_eq!(
            load_argv(),
            projected,
            "{release}: the vendored argv reference is not what this binary projects"
        );

        let _ = fs::remove_dir_all(&tmp);
    }
}

/// A live 0.153 binary is admissible, and a live 0.147 binary is too — the two-build
/// claim, checked against the real thing rather than against the file it was vendored
/// from.
#[test]
fn both_grounded_binaries_are_admissible() {
    if std::env::var("CC_CODEX_LIVE").as_deref() != Ok("1") {
        eprintln!("skipped: set CC_CODEX_LIVE=1 to run");
        return;
    }
    for env in ["CC_CODEX_0147", "CC_CODEX_0153"] {
        let Ok(bin) = std::env::var(env) else {
            eprintln!("skipped: {env} is not set");
            continue;
        };
        let left = codex_broker::guarded_surface::unadjudicated_against_baseline(Path::new(&bin))
            .unwrap_or_else(|e| panic!("{env}: {e}"));
        assert!(
            left.is_empty(),
            "{env}: the gate refuses this grounded binary: {}",
            left.join("; ")
        );
    }
}

/// **The class the argv projection cannot see.** `cloud-tasks` dispatches on both
/// binaries and appears in no enumeration either of them emits, so it is carried as a
/// hand-listed alias — and a hand-listed fact has to be re-measured or it rots.
///
/// The oracle is `codex <token> --help`: clap resolves the token first and prints the
/// resolved command's usage, so a dispatching alias prints `Usage: codex <target> …`
/// while a plain prompt word falls through to the root usage. That distinction is what
/// makes "this alias still dispatches" and "the completion script still omits it"
/// checkable rather than remembered.
#[test]
fn the_hidden_root_aliases_still_dispatch_and_are_still_hidden() {
    if std::env::var("CC_CODEX_LIVE").as_deref() != Ok("1") {
        eprintln!("skipped: set CC_CODEX_LIVE=1 to run");
        return;
    }
    for env in ["CC_CODEX_0147", "CC_CODEX_0153"] {
        let Ok(bin) = std::env::var(env) else {
            eprintln!("skipped: {env} is not set");
            continue;
        };
        let usage = |token: &str| -> String {
            let out = std::process::Command::new(&bin)
                .args([token, "--help"])
                .output()
                .expect("codex <token> --help");
            String::from_utf8_lossy(&out.stdout)
                .lines()
                .find(|l| l.trim_start().starts_with("Usage: codex"))
                .unwrap_or_default()
                .trim()
                .to_string()
        };
        // A word codex does not dispatch falls through to the root usage. This is the
        // control: without it, "prints a usage line" would prove nothing.
        let root = usage("thisisnotasubcommand");
        assert!(
            root.starts_with("Usage: codex [OPTIONS]"),
            "{env}: the dispatch oracle is broken; a non-subcommand printed {root:?}"
        );
        for alias in HIDDEN_ROOT_ALIASES {
            let resolved = usage(alias);
            assert_ne!(
                resolved, root,
                "{env}: `codex {alias}` no longer dispatches — the hidden-alias list is \
                 carrying a token that is not a token any more"
            );
        }

        // …and it is still invisible to every enumeration this binary emits, which is
        // the only reason it has to be hand-listed at all.
        for shell in ["bash", "zsh", "fish", "elvish", "powershell"] {
            let out = std::process::Command::new(&bin)
                .args(["completion", shell])
                .output()
                .expect("codex completion");
            let text = String::from_utf8_lossy(&out.stdout);
            for alias in HIDDEN_ROOT_ALIASES {
                assert!(
                    !text.contains(alias),
                    "{env}: `codex completion {shell}` now enumerates {alias:?} — take it \
                     out of HIDDEN_ROOT_ALIASES so the argv diff covers it instead"
                );
            }
        }
    }
}

/// **Every server→client request the broker will ANSWER must be one the binary actually
/// sends.**
///
/// The c2s side has a pinned census and an exhaustiveness proof; the s2c side has neither,
/// because s2c is a byte-exact passthrough and the only gate on it is the capability
/// observer. That gate names three methods by string — the two approvals and
/// `item/tool/call` — and a string that no longer matches anything fails SILENTLY: the
/// observer tombstones the id instead, the client's answer is dropped, and the exchange
/// the server opened is stranded. That is exactly the failure this round fixed, so the
/// names are tied to the binary's own `ServerRequest.json` rather than to memory.
///
/// Live, because there is no vendored s2c reference to check against offline — the honest
/// source for "what does this build send" is the build.
#[test]
fn the_answerable_server_requests_are_real_in_both_binaries() {
    if std::env::var("CC_CODEX_LIVE").as_deref() != Ok("1") {
        eprintln!("skipped: set CC_CODEX_LIVE=1 to run");
        return;
    }
    let answerable = [
        codex_broker::response_capability::COMMAND_EXEC_APPROVAL,
        codex_broker::response_capability::FILE_CHANGE_APPROVAL,
        codex_broker::response_capability::DYNAMIC_TOOL_CALL,
    ];
    for env in ["CC_CODEX_0147", "CC_CODEX_0153"] {
        let Ok(bin) = std::env::var(env) else {
            eprintln!("skipped: {env} is not set");
            continue;
        };
        let tmp = std::env::temp_dir().join(format!("cc-s2c-{}-{env}", std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        for bundle in BUNDLES {
            let out = tmp.join(bundle);
            let mut cmd = std::process::Command::new(&bin);
            cmd.args(["app-server", "generate-json-schema", "--out"])
                .arg(&out);
            if bundle == "experimental" {
                cmd.arg("--experimental");
            }
            assert!(cmd.status().expect("generate-json-schema runs").success());

            let raw = fs::read_to_string(out.join("ServerRequest.json")).expect("ServerRequest");
            let doc: Value = serde_json::from_str(&raw).expect("parses");
            let census: BTreeSet<String> = doc["oneOf"]
                .as_array()
                .expect("oneOf")
                .iter()
                .filter_map(|v| {
                    let m = v.get("properties")?.get("method")?;
                    m.get("const")
                        .and_then(Value::as_str)
                        .or_else(|| m.get("enum")?.as_array()?.first()?.as_str())
                        .map(str::to_string)
                })
                .collect();
            assert!(!census.is_empty(), "{env}/{bundle}: empty s2c census");
            for method in answerable {
                assert!(
                    census.contains(method),
                    "{env}/{bundle}: the capability observer will answer {method:?}, which \
                     this build does not send — the binding is dead and the frame it was \
                     meant to answer would be tombstoned instead"
                );
            }
        }
        let _ = fs::remove_dir_all(&tmp);
    }
}

/// The admissible surface is derived from the two references and the tables, so a
/// reference that drifted from the tables must fail here rather than at a launch.
#[test]
fn the_two_references_and_the_tables_agree() {
    for bundle in BUNDLES {
        let grounded = grounded_wire(bundle);
        assert!(
            diff_wire(&admissible_wire(bundle, &grounded), &grounded).is_empty(),
            "{bundle}: the tables do not bridge the vendored references"
        );
        let baseline = baseline_wire(bundle);
        assert!(
            diff_wire(&admissible_wire(bundle, &baseline), &baseline).is_empty(),
            "{bundle}: the baseline is no longer admissible"
        );
    }
    let grounded = grounded_argv();
    assert!(diff_argv(&admissible_argv(&grounded), &grounded).is_empty());
    let baseline = baseline_argv();
    assert!(diff_argv(&admissible_argv(&baseline), &baseline).is_empty());
}
